### PR TITLE
fix: resolved empty data bug in lux meter

### LINKED ISSUE #1400: empty data is being recorded in lux meter
**Actual Behaviour**

When the lux meter is not fetching any data still it stores a record of empty the data in the lux meter data list.

**Expected Behaviour**

The record should not be created when no data is fetched and snack bar should be shown when displaying "No data fetched"

**Steps to reproduce it**

Lux Meter Fragment -> check the data fetched before recording, if no data is being recorded then dont make a record.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Avjeet**
Fixes #1400 

**Changes**: 
Added if-else in lux meter fragment to check for empty data before storing in the realm database in the form of record.

**Screenshot/s for the changes**:Not a UI change

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[emptyfix.zip](https://github.com/fossasia/pslab-android/files/2433551/emptyfix.zip)

### CODE REVIEW

File: app/src/main/java/io/pslab/activity/LuxMeterActivity.java [hunk 1]
```diff
@@ -201,11 +201,14 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
-                    SharedPreferences.Editor editor = realmPreferences.edit();
-                    editor.putLong("uniqueCount", uniqueRef + 1);
-                    editor.commit();
+                    if(selectedFragment.saveDataInRealm(uniqueRef, locationPref, gpsLogger)){
+                        CustomSnackBar.showSnackBar(coordinatorLayout, getString(R.string.exp_data_saved), null, null);
+                        SharedPreferences.Editor editor = realmPreferences.edit();
+                        editor.putLong("uniqueCount", uniqueRef + 1);
+                        editor.commit();
+                    }else{
+                        CustomSnackBar.showSnackBar(coordinatorLayout, "No Data Fetched", null, null);
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/activity/LuxMeterActivity.java]: Please add this text to `strings.xml` and fetch from there

File: app/src/main/java/io/pslab/activity/LuxMeterActivity.java [hunk 2]
```diff
@@ -201,11 +201,14 @@ public boolean onOptionsItemSelected(MenuItem item) {
                     ((LuxMeterFragmentData) selectedFragment).stopSensorFetching();
                     invalidateOptionsMenu();
                     Long uniqueRef = realmPreferences.getLong("uniqueCount", 0);
-                    selectedFragment.saveDataInRealm(uniqueRef, locationPref, gpsLogger);
-                    CustomSnackBar.showSnackBar(coordinatorLayout, getString(R.string.exp_data_saved), null, null);
-                    SharedPreferences.Editor editor = realmPreferences.edit();
-                    editor.putLong("uniqueCount", uniqueRef + 1);
-                    editor.commit();
+                    if(selectedFragment.saveDataInRealm(uniqueRef, locationPref, gpsLogger)){
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/activity/LuxMeterActivity.java]: Give this code a reformat

File: app/src/main/java/io/pslab/fragment/LuxMeterFragmentData.java [hunk 3]
```diff
@@ -400,40 +400,46 @@ public void stopSensorFetching() {
...
-            if (location != null) {
-                sensorLogged.setLatitude(location.getLatitude());
-                sensorLogged.setLongitude(location.getLongitude());
+    public boolean saveDataInRealm(Long uniqueRef, boolean includeLocation, GPSLogger gpsLogger) {
+        boolean flag = luxRealmData.isEmpty();
+        if (!flag) {
+            realm.beginTransaction();
+
+            SensorLogged sensorLogged = realm.createObject(SensorLogged.class, uniqueRef);
+            sensorLogged.setSensor("Lux Meter");
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/fragment/LuxMeterFragmentData.java]: Goes to `strings.xml`

File: app/src/main/java/io/pslab/fragment/LuxMeterFragmentData.java [hunk 4]
```diff
@@ -400,40 +400,46 @@ public void stopSensorFetching() {
...
+            sensorLogged.setDateTimeStart(startTime);
+            sensorLogged.setDateTimeEnd(endTime);
+            sensorLogged.setTimeZone(TimeZone.getDefault().getDisplayName());
+
+            if (includeLocation && gpsLogger != null) {
+                Location location = gpsLogger.getBestLocation();
+                if (location != null) {
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/fragment/LuxMeterFragmentData.java]: Can we check location null in the 414 if block and reduce this?
