### PR TITLE
Fix #1674 save graph function implemeted

### LINKED ISSUE #1674: New Feature : Add functionality to save graph views in gallery
**Actual Behaviour**

Currently there is no functionality to save graphs

**Expected Behaviour**
User should be able to save the graph of some instance in gallery using a button click

**Steps to reproduce it**
N/A

**LogCat for the issue**
N/A

**Screenshots of the issue**
N/A

**Would you like to work on the issue?**
yes

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1674 

**Changes**: When save graph button is clicked on the data logger activity, if the log file alrady exist in the local storage then only the .jpg image of current graph is stored in the local storage, if user has deleted the log from local storage then the log file created and .jpg file is stored. 

So even if user deletes the log from local storage it can again be generated using the app, which was not possible earlier.

This feature is currently added to Lux meter and Baro meter
**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[save_graph.apk.zip](https://github.com/fossasia/pslab-android/files/3142153/save_graph.apk.zip)

@cweitat  @CloudyPadmal  @abhinavraj23  kindly review.

### CODE REVIEW

File: app/src/main/java/io/pslab/fragment/LuxMeterDataFragment.java [hunk 1]
```diff
@@ -313,9 +324,41 @@ public void playData() {
...
+        view.setDrawingCacheEnabled(true);
+        Bitmap b = view.getDrawingCache();
+        try {
+            b.compress(Bitmap.CompressFormat.JPEG, 100, new FileOutputStream(Environment.getExternalStorageDirectory().getAbsolutePath() +
+                    File.separator + CSV_DIRECTORY + File.separator + luxSensor.getSensorName() +
+                    File.separator + CSVLogger.FILE_NAME_FORMAT.format(new Date()) + "_graph.jpg" ));
+        } catch (FileNotFoundException e) {
+            e.printStackTrace();
+        }
     }
```
Comment (ho-dor) [inline app/src/main/java/io/pslab/fragment/LuxMeterDataFragment.java]: There are unnecessary extra spaces.

File: app/src/main/java/io/pslab/fragment/BaroMeterDataFragment.java [hunk 2]
```diff
@@ -16,7 +18,9 @@
 import android.view.ViewGroup;
 import android.widget.TextView;
 import android.widget.Toast;
+
```
Comment (ho-dor) [inline app/src/main/java/io/pslab/fragment/BaroMeterDataFragment.java]: Please remove extra spaces

File: app/src/main/java/io/pslab/fragment/LuxMeterDataFragment.java [hunk 3]
```diff
@@ -313,9 +324,41 @@ public void playData() {
...
 
+
```
Comment (ho-dor) [inline app/src/main/java/io/pslab/fragment/LuxMeterDataFragment.java]: Please remove extra spaces

File: app/src/main/java/io/pslab/fragment/BaroMeterDataFragment.java [hunk 4]
```diff
@@ -309,9 +322,39 @@ public void stopData() {
...
+            }
+        }
+        View view = rootView.findViewById(R.id.barometer_linearlayout);
+        view.setDrawingCacheEnabled(true);
+        Bitmap b = view.getDrawingCache();
+        try {
+            b.compress(Bitmap.CompressFormat.JPEG, 100, new FileOutputStream(Environment.getExternalStorageDirectory().getAbsolutePath() +
+                    File.separator + CSV_DIRECTORY + File.separator + baroSensor.getSensorName() +
+                    File.separator + CSVLogger.FILE_NAME_FORMAT.format(new Date()) + "_graph.jpg" ));
+        } catch (FileNotFoundException e) {
```
Comment (ho-dor) [inline app/src/main/java/io/pslab/fragment/BaroMeterDataFragment.java]: We can use string resource for "_graph.jpg" as it is used at multiple places.
