### PR TITLE
aligned sensor fragment files with coding style and removed redundant code

### LINKED ISSUE #513: align sensor fragment files with coding style and remove redundant code
**Actual Behaviour**

Currently there is some redundant code in sensor fragment files. 

**Expected Behaviour**

There shouldn't be redundant code and code should meet coding style.  

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by viveksb007**
Fixes #513 #315 

Changes: 
- Aligned sensor fragment files with coding style,optimised code and removed redundant code.

Apk for testing :  [app-debug.apk.tar.gz](https://github.com/fossasia/pslab-android/files/1222973/app-debug.apk.tar.gz)

### CODE REVIEW

File: app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentSHT21.java [hunk 1]
```diff
@@ -224,20 +207,20 @@ protected void onPostExecute(Void aVoid) {
             tvSensorSHT21Temp.setText(String.valueOf(dataSHT21Temp.get(0)));
             tvSensorSHT21Humidity.setText(String.valueOf(dataSHT21Humidity.get(0)));
 
-            LineDataSet dataset1 = new LineDataSet(entriesTemperature, "Ax");
-            LineDataSet dataset2 = new LineDataSet(entriesHumidity, "Ay");
+            LineDataSet dataSet1 = new LineDataSet(entriesTemperature, "Temperature");
```
Comment (CloudyPadmal) [inline app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentSHT21.java]: Can we use string resources here? :)

File: app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentTSL2561.java [hunk 2]
```diff
@@ -197,9 +191,9 @@ protected void onPostExecute(Void aVoid) {
             tvSensorTSL2561Infrared.setText(String.valueOf(dataTSL2561[1]));
             tvSensorTSL2561Visible.setText(String.valueOf(dataTSL2561[2]));
 
-            LineDataSet dataset1 = new LineDataSet(entriesfull, "full");
-            LineDataSet dataSet2 = new LineDataSet(entriesinfrared, "infrared");
-            LineDataSet dataSet3 = new LineDataSet(entriesvisible, "visible");
+            LineDataSet dataset1 = new LineDataSet(entriesFull, "Full");
+            LineDataSet dataSet2 = new LineDataSet(entriesInfrared, "Infrared");
+            LineDataSet dataSet3 = new LineDataSet(entriesVisible, "Visible");
```
Comment (CloudyPadmal) [inline app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentTSL2561.java]: In these cases as well?
