### PR TITLE
Fixes: PSLabSensor Activity decoupled from fragments

### LINKED ISSUE #2108: Use Interface Callbacks to reduce Coupling between Activity and Fragments and reduce the lines of code
**Actual Behaviour**
`PsLabSensor` directly calls methods from fragments such as `LuxMeterDataFragment,` `SoundMeterFragment` etc, which increases coupling and also increases lines of codes in the `onOptionItemSelected()` method of `PsLabSensor`. In addition it increases chances of introducing bugs when new sensors are implemented. 

**Expected Behaviour**
**Interface callbacks** can be used to reduce the coupling between `PsLabSensor` and other data fragments. We can define a interface with common set of methods such as play(), stop(), pause(), resume() etc and have the fragments implement this interface.

**Steps to reproduce it**
`N/A`

**LogCat for the issue**

`N/A`

**Screenshots of the issue**
The lines of codes below are redundant.
coupling_issue

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by VIKAS9899**
Fixes #2108

**Changes**: PSLabSensorActivity will interact with OperationCallback for operation not any specific fragments by doing this we can eliminate coupling & reduce boilerplate code.

### CODE REVIEW

File: app/src/main/java/io/pslab/models/PSLabSensor.java [hunk 1]
```diff
@@ -335,65 +339,21 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
-                        ((DustSensorDataFragment) getSupportFragmentManager()
-                                .findFragmentByTag(getSensorName())).playData();
-                    } else if(getSensorFragment() instanceof SoundMeterDataFragment) {
-                        ((SoundMeterDataFragment) getSupportFragmentManager()
-                                .findFragmentByTag(getSensorName())).playData();
+                     fragment=getSupportFragmentManager()
+                            .findFragmentByTag(getSensorName());
+
+                    if (fragment instanceof OperationCallback){
+                        ((OperationCallback) fragment).playData();
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/models/PSLabSensor.java:346]: Reformat the code here. You can use automatic option in Android studio. It will add missing spaces and indents.

File: app/src/main/java/io/pslab/models/PSLabSensor.java [hunk 2]
```diff
@@ -335,65 +339,21 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
-                } else if (getSensorFragment() instanceof DustSensorDataFragment) {
-                    ((DustSensorDataFragment) getSupportFragmentManager()
-                            .findFragmentByTag(getSensorName())).stopData();
-                } else if(getSensorFragment() instanceof SoundMeterDataFragment) {
-                    ((SoundMeterDataFragment) getSupportFragmentManager()
-                            .findFragmentByTag(getSensorName())).stopData();
+                 fragment=getSupportFragmentManager()
+                        .findFragmentByTag(getSensorName());
+
+                if (fragment instanceof OperationCallback){
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/models/PSLabSensor.java:355]: Similar reformatting here

File: app/src/main/java/io/pslab/models/PSLabSensor.java [hunk 3]
```diff
@@ -420,33 +380,11 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
-                    ((DustSensorDataFragment) getSupportFragmentManager()
-                            .findFragmentByTag(getSensorName())).saveGraph();
-                } else if(getSensorFragment() instanceof SoundMeterDataFragment) {
-                    ((SoundMeterDataFragment) getSupportFragmentManager()
-                            .findFragmentByTag(getSensorName())).saveGraph();
+                 fragment=getSupportFragmentManager()
+                        .findFragmentByTag(getSensorName());
+
+                if (fragment instanceof OperationCallback){
+                    ((OperationCallback) fragment).saveGraph();
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/models/PSLabSensor.java:387]: Here as well

**Comment by VIKAS9899** [comment]
> @VIKAS9899 thank you for the pull request. Seems good. Can you build the APK file and upload here so that we can test it? Also I have requested some code refactoring changes. Thanks again.

@CloudyPadmal I have refracted the code. Please find the APK below

https://drive.google.com/file/d/1H9k2Cs57xeW-3suS-MlLtiSWBeZkuOlJ/view?usp=sharing
