### PR TITLE
fix:solved the issue of multimeter crash while recording

### LINKED ISSUE #1466: Unexpected Crash when recording at multimeter
**Actual Behaviour**
In multimeter , unexpected crash occurs on pressing delete after pausing the recording .
Please state here what is currently happening.

**Expected Behaviour**
The app should work smoothly.
State here what the feature should enable the user to do.

**Steps to reproduce it**
Go to multimeter , click on record , then pause and then on delete .
Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**Screenshots of the issue**
screenshot2

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**
No , just a review

### PR DESCRIPTION
**Pull request by abhinavraj23**
Fixes #1466 

**Changes**:
Restricted data recording only while PSLab is connected

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 

[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/2729320/app-debug.apk.zip)

### CODE REVIEW

File: app/src/main/java/io/pslab/activity/MultimeterActivity.java [hunk 1]
```diff
@@ -393,26 +393,30 @@ public boolean onCreateOptionsMenu(Menu menu) {
...
+                        item.setIcon(R.drawable.pause_icon);
+                        if (!isRecordingStarted) {
+                            multimeterLogger = new CSVLogger(getString(R.string.multimeter));
+                            isRecordingStarted = true;
+                            recordData = true;
+                            CustomSnackBar.showSnackBar(coordinatorLayout, getString(R.string.data_recording_start), null, null, Snackbar.LENGTH_LONG);
+                        }
+                    }
+                } else {
+                    CustomSnackBar.showSnackBar(coordinatorLayout, getString(R.string.nothing_to_record), null, null, Snackbar.LENGTH_LONG);
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/activity/MultimeterActivity.java]: Since this else block is functioning only if PSLab is not connected, we can put the same "PSLab not connected" message here instead of a new one.

**Comment by abhinavraj23** [comment]
Sure @CloudyPadmal

**Comment by abhinavraj23** [comment]
@CloudyPadmal I have solved the issue

**Comment by abhinavraj23** [comment]
@cweitat @harsh-2711 Please review it
