### PR TITLE
Fix: Logged data not shown for Gas Sensor.

### LINKED ISSUE #1984: Logged data not shown for gas sensor
**Actual Behaviour**

No logged data shown after recording in gas sensor.

**Expected Behaviour**

Recorded data should be shown after recording.

**Steps to reproduce it**

Record data on gas sensor and open logged data.

**LogCat for the issue**

N/A

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by VIKAS9899**
Fixes #1984

**Changes**: 
Entry would be created for case when device is not created to Gas sensor.

**Video for the change**: https://github.com/VIKAS9899/LogRepo/raw/master/Upload/2020_05_17_14_42_40.mp4

**APK for testing**: https://github.com/VIKAS9899/LogRepo/raw/master/Upload/pslab_1984.apk

### CODE REVIEW

File: app/src/main/java/io/pslab/fragment/GasSensorDataFragment.java [hunk 1]
```diff
@@ -397,6 +397,7 @@ private void visualizeData() {
                 mChart.invalidate();
             }
         }
+        writeLogToFile(System.currentTimeMillis(), (float) ppmValue);
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/fragment/GasSensorDataFragment.java:400]: Do we need to cast the double to float? What if the variable is set to float in the first place?

**Comment by CloudyPadmal** [comment]
Also squash commits into one and stick to the PR template.

File: app/src/main/java/io/pslab/fragment/GasSensorDataFragment.java (hunk 1 above)
Comment (fcartegnie) [reply app/src/main/java/io/pslab/fragment/GasSensorDataFragment.java:400]: https://docs.oracle.com/javase/specs/jls/se8/html/jls-5.html#jls-5.3

**Review by CloudyPadmal — APPROVED** [review]
