### PR TITLE
Fixes #388 : NFET Output characteristics experiment

### LINKED ISSUE #388: Add N-FET Output Characteristics Experiment
**Actual Behaviour**

Experiment Setup doesn't contain experiments related to N-FETs.

**Expected Behaviour**

N-FET experiments need to be implemented in the application

**Steps to reproduce it**

1. Open App
2. Go to `Saved Experiments` and observe

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes!

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes issue #388 

Changes: 
- Implemented NFET output characteristics experiment by setting PV1 and PV2 to Drain and Gate pins while measuring voltage across DS junction

Screenshots for the change: 

fix

APK for testing
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1198207/app-debug.apk.zip)

### CODE REVIEW

File: app/src/main/java/org/fossasia/pslab/experimentsetup/NFETOutputCharacteristicsExperiment.java [hunk 1]
```diff
@@ -0,0 +1,221 @@
...
+                                }
+
+                                initialVoltage = Float.parseFloat(etInitialVoltage.getText().toString());
+                                finalVoltage = Float.parseFloat(etFinalVoltage.getText().toString());
+                                totalSteps = Float.parseFloat(etStepSize.getText().toString());
+                                gateVoltage = Float.parseFloat(etGateVoltage.getText().toString());
+                                stepVoltage = (finalVoltage - initialVoltage) / totalSteps;
+
+                                if (scienceLab.isConnected()) {
+                                    scienceLab.setGain("CH1", 2, false);
```
Comment (viveksb007) [inline app/src/main/java/org/fossasia/pslab/experimentsetup/NFETOutputCharacteristicsExperiment.java]: Move ```scienceLab.setGain()``` to ```runnable``` that you are passing to thread below.

Comment (viveksb007) [inline app/src/main/java/org/fossasia/pslab/experimentsetup/NFETOutputCharacteristicsExperiment.java]: Move ```scienceLab.setGain()``` to ```runnable``` that you are passing to thread below.

File: app/src/main/java/org/fossasia/pslab/experimentsetup/NFETOutputCharacteristicsExperiment.java [hunk 2]
```diff
@@ -198,9 +198,9 @@ protected Void doInBackground(Float... params) {
             float voltage = params[0];
             scienceLab.setPV1(voltage);
             float readVoltage = (float) scienceLab.getVoltage("CH1", 10);
-            voltageAxis.add(readVoltage);
-            float resistance = 560;
-            currentAxis.add((voltage - readVoltage) / resistance);
+            voltageAxis.add(Math.abs(readVoltage - 3));
+            float resistance = 56;
```
Comment (viveksb007) [inline app/src/main/java/org/fossasia/pslab/experimentsetup/NFETOutputCharacteristicsExperiment.java]: Could you tell a little about these parameters changes like resistance 56 instead of 560 and adding modified voltage to axis-values

Comment (CloudyPadmal) [inline app/src/main/java/org/fossasia/pslab/experimentsetup/NFETOutputCharacteristicsExperiment.java]: Oops ! That's a mistake. I was playing with the device with some weird values after I've made the PR and forgot that they are still there when I shifted the gain set method call! I'll revert those back and make a quick commit!!!

**Comment by CloudyPadmal** [comment]
Thanks @viveksb007 and @asitava1998 :+1:
