### PR TITLE
Fixes #327 : Progress Dialog for device initialization

### LINKED ISSUE #327: Add a progress dialog to home screen to show device initialization
**Actual Behaviour**

When the device is being initialized, it is displayed in a text view

**Expected Behaviour**

Device initialization can be shown using a progress dialog box

**Steps to reproduce it**

1. Open App
2. Connect device and observe the initialization text

**LogCat for the issue**

> Not available

**Screenshots of the issue**

initwait

**Would you like to work on the issue?**

Yes!

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes issue #327 

Changes: 
- Added a progress dialog box to display device initialization in home fragment

Screenshots for the change: 
[Screencast](https://drive.google.com/open?id=0B5su2_aUn8g7TmlnMWlXa1I2VDQ)

### CODE REVIEW

File: app/src/main/java/org/fossasia/pslab/fragment/HomeFragment.java [hunk 1]
```diff
@@ -82,6 +89,7 @@ public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
         super.onViewCreated(view, savedInstanceState);
 
         if (deviceConnected) {
+            progressDialog.show();
```
Comment (viveksb007) [inline app/src/main/java/org/fossasia/pslab/fragment/HomeFragment.java]: This would create progress dialog when switching between fragments.
Try showing progress dialog when read version string from device.

Comment (CloudyPadmal) [inline app/src/main/java/org/fossasia/pslab/fragment/HomeFragment.java]: Thanks for the review @viveksb007 ! I shifted the place! :+1:

**Comment by CloudyPadmal** [comment]
Thanks guys for the review! :+1:
