### PR TITLE
Thermometer working added and crash fixed

### LINKED ISSUE #1750: Adding the working of thermometer
**Actual Behaviour**

Only UI created so far.

**Expected Behaviour**

Adding the backend implementation of thermometer.

**Steps to reproduce it**

N/A

**LogCat for the issue**

N/A

**Screenshots of the issue**

N/A

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by ho-dor**
Fixes #1750 #1752 

**Changes**: Added backend code for thermometer . 

**Screenshot/s for the changes**: 
Screenshot_20190529-185838_PSLab

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[app-debug.zip](https://github.com/fossasia/pslab-android/files/3237006/app-debug.zip)

### CODE REVIEW

File: app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java [hunk 1]
```diff
@@ -1,111 +1,218 @@
...
+    private int count = 0, turns = 0;
+    private float sum = 0;
+    private boolean returningFromPause = false;
+
+    private float tempValue = -1;
+
+    private enum THERMOMETER_SENSOR {INBUILT_SENSOR, TSL2561_SENSOR}
+
+    @BindView(R.id.thermo_max)
+    TextView statMax;
```
Comment (adityastic) [inline app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java]: All can be private

File: app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java [hunk 2]
```diff
@@ -117,30 +224,89 @@ public void playData() {
...
-        thermometerActivity.invalidateOptionsMenu();
-    }
+    private void processRecordedData(long timeGap) {
+        final Handler handler = new Handler();
+        if (graphTimer != null) {
+            graphTimer.cancel();
+        } else {
+            graphTimer = new Timer();
+        }
+        graphTimer.schedule(new TimerTask() {
```
Comment (adityastic) [inline app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java]: Never use TimerTask anonymously. This is a memory leak @CloudyPadmal

File: app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java (hunk 1 above)
Comment (CloudyPadmal) [reply app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java]: Bindviews cannot be made private. Throws an error.

File: app/src/main/res/layout/activity_thermometer.xml [hunk 3]
```diff
@@ -1,36 +1,137 @@
...
+                android:orientation="vertical">
+
+                <com.github.anastr.speedviewlib.PointerSpeedometer
+                    android:id="@+id/thermo_meter"
+                    android:layout_width="match_parent"
+                    android:layout_height="@dimen/speedometer_height"
+                    android:padding="15dp"
+                    app:sv_speedTextColor="@color/black"
+                    app:sv_speedTextPosition="BOTTOM_CENTER"
+                    app:sv_speedTextSize="@dimen/lux_display_font_size"
```
Comment (CloudyPadmal) [inline app/src/main/res/layout/activity_thermometer.xml]: Can you make separate variables for thermometer replacing the `lux`s?

File: app/src/main/res/values/strings.xml [hunk 4]
```diff
@@ -787,4 +787,7 @@
     <string name="thermometer_bottom_sheet_text">Thermometer instrument is used to measure ambient temprature. It can be measured using inbuilt ambient temprature sensor or through SHT21.</string>
     <string name="thermometer_bottom_sheet_desc">Thermometer instrument is used to measure ambient temprature. It can be measured using inbuilt ambient temprature sensor or through SHT21.</string>
     <string name="no_thermometer_sensor">Device does not have Thermometer Sensor</string>
+    <string name="thermo_unit">F</string>
```
Comment (CloudyPadmal) [inline app/src/main/res/values/strings.xml]: We'll use Celcius

Comment (CloudyPadmal) [reply app/src/main/res/values/strings.xml]: And let user select which unit want from configurations

File: app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java [hunk 5]
```diff
@@ -152,71 +318,266 @@ private void playRecordedData() {
...
+            if (timeElapsed != previousTimeElapsed) {
+                previousTimeElapsed = timeElapsed;
+                Entry entry = new Entry((float) timeElapsed, tempValue);
+                Long currentTime = System.currentTimeMillis();
+                writeLogToFile(currentTime, tempValue);
+                entries.add(entry);
+
+                count++;
+                sum += entry.getY();
+                statMean.setText(String.format(Locale.getDefault(), PSLabSensor.LUXMETER_DATA_FORMAT, (sum / count)));
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java]: All these `Lux` stuff need to be thermo related

File: app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java (hunk 1 above)
Comment (adityastic) [reply app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java]: @CloudyPadmal ok sir

**Comment by neel1998** [comment]
@ho-dor  @CloudyPadmal  Do we need max value of temperature to be 10000 F! Isn't it too high?

**Comment by CloudyPadmal** [comment]
@neel1998 definitely no. @ho-dor check the datasheet of the sensor and set the max value to the maximum temperature value in that.

**Comment by CloudyPadmal** [comment]
Besides, i think a gauge is not a good way to represent data in a thermometer. We can implement some color bar instead. Please look into this @ho-dor . Thanks.

File: app/src/main/res/layout/activity_thermometer.xml (hunk 3 above)
Comment (ho-dor) [reply app/src/main/res/layout/activity_thermometer.xml]: No . I kept it the same knowigly because the dimen value are going to be same eventually in UI but I will change it if that is better

File: app/src/main/res/values/strings.xml (hunk 4 above)
Comment (ho-dor) [reply app/src/main/res/values/strings.xml]: Yes , I am going to add that functionality . I just wanted to confirm it works or not till here.

File: app/src/main/res/layout/activity_thermometer.xml (hunk 3 above)
Comment (CloudyPadmal) [reply app/src/main/res/layout/activity_thermometer.xml]: Yes, all needs to be changed. The real reason why we are using resources instead of hard-coded values is that, it will be easier and practical to make modifications from one place. Putting luxmeter dimensions is in fact similar to hard-coding.

File: app/src/main/res/values/strings.xml (hunk 4 above)
Comment (CloudyPadmal) [reply app/src/main/res/values/strings.xml]: I was referring to units here. Throughout the app we are using Metric units, not imperial

**Comment by ho-dor** [comment]
> Besides, i think a gauge is not a good way to represent data in a thermometer. We can implement some color bar instead. Please look into this @ho-dor . Thanks.

How about we change the background of gauge as the temp changes, like make it green for low temp and red for higher temp ?

**Comment by CloudyPadmal** [comment]
> > Besides, i think a gauge is not a good way to represent data in a thermometer. We can implement some color bar instead. Please look into this @ho-dor . Thanks.
> 
> How about we change the background of gauge as the temp changes, like make it green for low temp and red for higher temp ?

Ok for now. Blue for low temps and red for high temps

**Comment by ho-dor** [comment]
@neel1998 @CloudyPadmal please check

File: app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java [hunk 6]
```diff
@@ -1,111 +1,219 @@
...
 import android.hardware.SensorEvent;
 import android.hardware.SensorEventListener;
 import android.hardware.SensorManager;
 import android.location.Location;
 import android.os.Bundle;
+import android.os.Environment;
 import android.os.Handler;
 import android.support.annotation.NonNull;
-import android.support.annotation.Nullable;
+import android.support.v14.preference.PreferenceFragment;
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java]: Codacy complains this as unused

**Comment by CloudyPadmal** [comment]
Rest looks ok. We can progress from here

**Comment by neel1998** [comment]
Looks ok to me as well

**Comment by ho-dor** [comment]
codacy resolved

**Comment by ho-dor** [comment]
Once this gets merged , I will make a PR for #1756. @CloudyPadmal @neel1998

**Comment by ho-dor** [comment]
I have changed the sensor to SHT21 as that is more suitable for this purpose.

**Comment by neel1998** [comment]
@ho-dor  there is still one unused import in codacy. Remove it in this PR or remember to remove in next one. Also can you send the latest apk once to test

**Comment by ho-dor** [comment]
@neel1998 check

**Comment by neel1998** [comment]
Can you comment the apk file here?

**Comment by ho-dor** [comment]
> Can you comment the apk file here?


The apk file isn't supported to upload here . I have added the latest zip of apk in PR

**Comment by neel1998** [comment]
The graph is acting weirdly. Please look at the gif. It goes blank after a while. Please look at the barometer graph. It seems to be working okay

**Comment by ho-dor** [comment]
I have increased the range on x-axis and the graph is more like lux meter. I am unable to understand the graph of baro meter as the max value that pressure can reach is 2 according to the range but the graph only shows till 0.45 atm on y-axis.

**Comment by neel1998** [comment]
This has nothing to do with range, the x - axis should increment every second, which is not happening in the thermometer, also the graph going blank after a while is also not an issue of range

**Comment by ho-dor** [comment]
> This has nothing to do with range, the x - axis should increment every second, which is not happening in the thermometer, also the graph going blank after a while is also not an issue of range

I have  set the graph updation period to 100 ms in place of 1000 ms that is why it is getting updated quick , but the graph going blank is because of the x-axis range that I have set to 800 now , if you will see , now the graph continues till 800 s earlier it was till 80 s.

**Comment by neel1998** [comment]
So have you changed to 1000 ms?

**Comment by ho-dor** [comment]
Yes , check the updated apk

**Comment by neel1998** [comment]
looks good now
