### PR TITLE
fix: added snackbar and small ui changes in lux meter.

### LINKED ISSUE #2746: Lux meter improvement
Following needs to be changed in lux meter

## Snackbar Integration:

Notifies users when:

- The device does not have a light sensor.
- App does not have access to light sensor.

## UI changes

- Make the edge of chart straight.
- Add padding to the right of the chart to make it  center.

### PR DESCRIPTION
**Pull request by Yugesh-Kumar-S**
Fixes  #2746
   

## Changes 
- Added a snackbar to notify light sensor errors like "not available" , "cannot access sensor".
- Changed curved edges of chart 
-  Added padding to the right side of chart.

## Screenshots / Recordings  

image

**Checklist**: 
- [x] **No hard coding**: I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard coding any value.
- [x] **No end of file edits**: No modifications done at end of resource files `strings.xml`, `dimens.xml` or `colors.xml`.
- [x] **Code reformatting**: I have reformatted code and fixed indentation in every file included in this pull request.
- [x] **No extra space**: My code does not contain any extra lines or extra spaces than the ones that are necessary.

## Summary by Sourcery

Add snackbar notifications for light sensor errors, refactor sensor initialization and disposal, and adjust the lux meter chart’s UI styling and layout.

New Features:
- Display a floating SnackBar for light sensor errors such as unavailable sensor or access denial
- Implement platform-specific error callbacks for unsupported platforms and sensor failures

Enhancements:
- Refactor LuxMeterStateProvider lifecycle to initialize sensors in initState and dispose resources properly
- Update chart styling: remove container border radius, add dynamic padding and right-side inset, and adjust axis reserved sizes

### CODE REVIEW

File: lib/constants.dart [hunk 1]
```diff
@@ -231,3 +231,9 @@ String soundMeterError = 'Sound sensor error:';
 String soundMeterInitialError = 'Sound sensor initialization error:';
 String db = 'dB';
 String soundMeterTitle = 'Sound Meter';
+String luxMeterIOSError = "App doesn't have access to the light sensor";
+String luxMeterDesktopError = "Light sensor not supported on desktop";
+String luxMeterWebError = "Light sensor not supported on web";
+String luxMeterPlatformError = "Light sensor not supported on this platform";
+String noLightSensor = "Device does not have light sensor";
```
Comment (CloudyPadmal) [inline lib/constants.dart]:
```suggestion
String noLightSensor = "Device does not have a light sensor";
```

**Review by CloudyPadmal — APPROVED** [review]

File: lib/providers/luxmeter_state_provider.dart [hunk 2]
```diff
@@ -22,33 +22,83 @@ class LuxMeterStateProvider extends ChangeNotifier {
...
+        cancelOnError: false,
       );
     } catch (e) {
       logger.e("$lightSensorInitialError $e");
+      _handleSensorError(e);
     }
   }
 
+  bool _isPlatformSupported() {
+    return Platform.isAndroid;
```
Comment (AsCress) [inline lib/providers/luxmeter_state_provider.dart]: Can't we query fetch this from the library directly, if the platform is supported ? 
Would be better than explicitly mentioning and handling for all platforms separately here.
Or maybe, just handle this once, if the device doesn't have a light sensor, we throw an error simple, regardless of the platform. Let's keep it simple here.

**Review by AsCress — CHANGES_REQUESTED** [review]

File: lib/providers/luxmeter_state_provider.dart (hunk 2 above)
Comment (Yugesh-Kumar-S) [reply lib/providers/luxmeter_state_provider.dart]: hi @AsCress , first i have tried it (throw exception if device doesnt have light sensor ) , but windows and web did not throw exception for sensor not available , So i had to address each platform.

Comment (AsCress) [reply lib/providers/luxmeter_state_provider.dart]: @Yugesh-Kumar-S Then what happens to the Stream on these platforms ? Does it get events ?

Comment (Yugesh-Kumar-S) [reply lib/providers/luxmeter_state_provider.dart]: @AsCress I have made the changes as suggested (No platform specific). Now the Snackbar is thrown if no sensor data is received for 3 seconds.

**Comment by AsCress** [comment]
@Yugesh-Kumar-S This is good to go. Please resolve conflicts here.

**Comment by Yugesh-Kumar-S** [comment]
> @Yugesh-Kumar-S This is good to go. Please resolve conflicts here.

Done.

**Review by CloudyPadmal — APPROVED** [review]

**Comment by Yugesh-Kumar-S** [comment]
@AsCress Please review and merge this PR . I need to create a PR for luxmeter configuration screen.

**Review by AsCress — APPROVED** [review]
