### PR TITLE
Fixes #511 Fixed buggy behaviour of control main fragment

### LINKED ISSUE #511: editTextValue changed on Set button click in Control Main
**Actual Behaviour**

After seekbar is changed from default value, when `Set` button is clicked it changes editText value at each click.

**Expected Behaviour**

On clicking `Set` button only pslab device should be configured, EditText value shouldn't change. 

**Steps to reproduce it**

Control Main -> Change seekbar of W1 -> click on `Set` button again and again, value of edit text would change on each click. 

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by viveksb007**
Fixes issue #511 

Changes:
- Prevented unwanted trigger in EditText value by SeekBar.
- Modified map() function to support double data types.

apk for testing : 
[app-debug.apk.tar.gz](https://github.com/fossasia/pslab-android/files/1221796/app-debug.apk.tar.gz)

### CODE REVIEW

File: app/src/main/java/org/fossasia/pslab/adapters/ControlMainAdapter.java [hunk 1]
```diff
@@ -550,14 +597,16 @@ else if (value > 5000)
                     }
                 });
 
-                seekBarControlMain.setMax(5000);
```
Comment (viveksb007) [inline app/src/main/java/org/fossasia/pslab/adapters/ControlMainAdapter.java]: Because previously range of seekbar was 0-5000 but allowed values were 10-5000. So they were not accurately mapped. 0-4990 -> 10-5000 hope this clears the doubt.

Comment (CloudyPadmal) [inline app/src/main/java/org/fossasia/pslab/adapters/ControlMainAdapter.java]: Yea it does! Thanks @viveksb007 :+1:
