### PR TITLE
Fix #1783 robotic arm save crash fixed

### LINKED ISSUE #1783: Robotic Arm: App Constantly Crashes when Hitting Saving Button
Trying to save using the saving button results in app crash on Xiaomi Redmi Android 7.1.2

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1783 

**Changes**: Robotic arm saving timeline crash fixed

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[robotic_arm_save_crash.zip](https://github.com/fossasia/pslab-android/files/3273820/robotic_arm_save_crash.zip)

@CloudyPadmal  @mariobehling  @ho-dor have a look at this

### CODE REVIEW

**Comment by ho-dor** [comment]
@neel1998 i think this needs to be checked on Xiaomi Redmi Android 7.1.2 as mentioned in the issue as it was working on my device anyway.

File: app/src/main/java/io/pslab/activity/RoboticArmActivity.java [hunk 1]
```diff
@@ -442,8 +442,12 @@ private void saveTimeline() {
             }
             if (gpsLogger.isGPSEnabled()) {
                 Location location = gpsLogger.getDeviceLocation();
-                lat = location.getLatitude();
-                lon = location.getLongitude();
+                if (location != null) {
+                    lat = location.getLatitude();
+                    lon = location.getLongitude();
+                } else {
+                    lat = lon = 0.0;
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/activity/RoboticArmActivity.java]: We'll do this line by line
