### PR TITLE
Java Docs for methods in ScienceLab class

### LINKED ISSUE #1833: Add JavaDocs to ScienceLab.java class
**Actual Behaviour**

[`ScienceLab.java`](https://github.com/fossasia/pslab-android/blob/development/app/src/main/java/io/pslab/communication/ScienceLab.java) class got no documentation.

**Expected Behaviour**

Each function should be well documented with JavaDocs so that it will be helpful for new developers to understand the code

**Steps to reproduce it**

Check out [`ScienceLab.java`](https://github.com/fossasia/pslab-android/blob/development/app/src/main/java/io/pslab/communication/ScienceLab.java)  class

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

@neel1998 and @ho-dor , I suggest you resolve this issue as part by part. Whenever you are using a function in ScienceLab class, read through that function well and add JavaDocs to that specific function. Let's progress through that way.

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1833 

**Changes**: Java Docs for Analog section added

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
@neel1998 regarding the current pwmsqr function, thought you'd have followed what's mentioned in #1833 
> Whenever you are using a function in ScienceLab class, read through that function well and add JavaDocs to that specific function.

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 1]
```diff
@@ -82,6 +82,9 @@
     private NRF24L01 nrf;
     private MCP4728 dac;
 
+    /**Constructor
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: Space between *<>Con...

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 2]
```diff
@@ -480,6 +483,9 @@ private void runInitSequence(Boolean loadCalibrationData) throws IOException {
         }
     }
 
+    /**
+     * @return Resistance of connected resistor
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: ... of connected resistor between RES and GND pins

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 3]
```diff
@@ -526,10 +532,25 @@ public void close() {
         }
     }
 
+    /**
+     * Blocking call that fetches an oscilloscope trace from the specified input channel
+     * @param channel Channel to select as input. ['CH1'..'CH3','SEN']
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: List all the channels. This is the direct documentation for a developer to refer to.

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 4]
```diff
@@ -548,6 +569,14 @@ public void close() {
         return retData;
     }
 
+    /**
+     * Blocking call that fetches oscilloscope traces from CH1,CH2,CH#,MIC
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: `#` ?

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 5]
```diff
@@ -682,6 +718,18 @@ else if (args.contains("FIRE_PULSES")) {
         }
     }
 
+    /**
+     * Blocking call that fetches oscilloscope traces from a single oscilloscope channel at a maximum speed of 2MSPS
+     * @param channel Channel name 'CH1' / 'CH2' ... 'SEN'
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: List all channels

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 6]
```diff
@@ -794,6 +850,15 @@ else if (args.contains("READ_CAP")) {
         return null;
     }
 
+    /**
+     * Instruct the ADC to start sampling. use fetchTrace to retrieve the data
+     * @param number Channels to acquire. 1/2/4
+     * @param samples Total points to store per channel. Maximum 3200 total
+     * @param timeGap  Timegap between two successive samples (in uSec)
+     * @param channelOneInput Map channel 1 to 'CH1' ... 'CH9'
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: CH9?

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 7]
```diff
@@ -984,6 +1065,17 @@ public boolean fetchChannelOneShot(int channelNumber) {
         return true;
     }
 
+    /**
+     * Configure trigger parameters for 10-bit capture commands
+     * The capture routines will wait till a rising edge of the input signal crosses the specified level.
+     * The trigger will timeout within 8mS, and capture routines will start regardless.
+     * These settings will not be used if the trigger option in the capture routines are set to False
+     * @param channel Channel 0,1,2,3. Corresponding to the channels being recorded by the capture routine(not the analog inputs)
+     * @param channelName Name of the channel. 'CH1'... 'V+'
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: List all valid channels as input everywhere

**Comment by neel1998** [comment]
@CloudyPadmal  I have made the changes you requested. Can we merge this for now, more docs an be added on the go

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 8]
```diff
@@ -1588,6 +1798,21 @@ else if ("falling".equals(edgeType2))
         return null;
     }
 
+    /**
+     * Log timestamps of rising/falling edges on one digital input
+     * @param waitingTime Total time to allow the logic analyzer to collect data. This is implemented using a simple sleep routine, so if large delays will be involved, refer to startOneChannelLA() to start the acquisition, and fetchLAChannels() to retrieve data from the hardware after adequate time. The retrieved data is stored in the array self.dchans[0].timestamps.
+     * @param aquireChannel ID1',...,'ID4'
+     * @param triggerChannel ID1',...,'ID4'
+     * @param aquireMode EVERY_SIXTEENTH_RISING_EDGE = 5
```
Comment (ho-dor) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: @neel1998 according to the changes requested by @CloudyPadmal , I think here as well all the ID should be mentioned for aquireChannel and triggerChannel params

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 9]
```diff
@@ -1612,6 +1837,14 @@ else if ("falling".equals(edgeType2))
         return retData;
     }
 
+    /**
+     * Start logging timestamps of rising/falling edges on ID1
```
Comment (ho-dor) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: @neel1998 there is duplicate on line 1850. I think we should keep it here and remove from 1850 since documentation should contain the info of channel.

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 10]
```diff
@@ -526,10 +532,25 @@ public void close() {
         }
     }
 
+    /**
+     * Blocking call that fetches an oscilloscope trace from the specified input channel
+     * @param channel Channel to select as input. ['CH1','CH2','CH3','MIC',SEN']
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: No `SEN` pin. Mention it's `RES` pin or `VOL` instead

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 11]
```diff
@@ -548,6 +569,14 @@ public void close() {
         return retData;
     }
 
+    /**
+     * Blocking call that fetches oscilloscope traces from CH1,CH2,CH3,MIC
+     * @param samples Number of samples to fetch. Maximum 2500
+     * @param timeGap Timegap between samples in microseconds. Minimum 1.75uS
+     * @param traceOneRemap Choose the analog input for channel 1. It is connected to CH1 by default. Channel 2 always reads CH2.
+     * @param trigger boolean whether trigger is selected or not
+     * @return Arrays X(timestamps),Y1(Voltage at CH1),Y2(Voltage at CH2),Y3(Voltage at CH3),Y4(Voltage at CH4)
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: Add some linebreaks to make it easier to read

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 12]
```diff
@@ -567,6 +596,13 @@ public void close() {
         return retData;
     }
 
+    /**
+     * Blocking call that fetches oscilloscope traces from a set of specified channels
+     * @param samples Number of samples to fetch. Maximum 10000/(total specified channels)
+     * @param timeGap Timegap between samples in microseconds.
+     * @param args Channel names
+     * @return Arrays X(timestamps),Y1,Y2 ..
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: .. means

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 13]
```diff
@@ -732,6 +780,14 @@ else if (args.contains("READ_CAP")) {
         }
     }
 
+    /**
+     *
+     * @param channel Channel name 'CH1' / 'CH2' ... 'SEN'
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: Please double check for these errors. Need all channels
