### PR TITLE
fix: App crash when back button is pressed in Import Log

### LINKED ISSUE #1707: Bug: App crashes when back is pressed with no file is selected in import log menu
**Actual Behaviour**
App crashes when back button(No file is selected) is pressed after selecting import log from logged data menu.
**Expected Behaviour**
App should return to the logged data activity instead of crashing.
**Steps to reproduce it**
Open app -> Logged data from navigation menu -> Import Log from top right menu -> select any one option -> without selecting any file from the opened intent, press back.
**Screenshots of the issue**

**Would you like to work on the issue?**
Yes, I would like to work.

### PR DESCRIPTION
**Pull request by Smit2010**
Fixes #1707 

**Screenshot/s for the changes**:

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

### CODE REVIEW

File: app/src/main/java/io/pslab/activity/DataLoggerActivity.java [hunk 1]
```diff
@@ -221,11 +221,13 @@ private void selectFile() {
     @Override
     protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
         if (requestCode == 100) {
-            Uri uri = data.getData();
-            String path = uri.getPath();
-            path = path.replace("/root_path/", "/");
-            File file = new File(path);
-            getFileData(file);
+            if (data != null) {
```
Comment (adityastic) [inline app/src/main/java/io/pslab/activity/DataLoggerActivity.java]: Never check for data is null, check for resultCode is ok

Comment (adityastic) [reply app/src/main/java/io/pslab/activity/DataLoggerActivity.java]: And add a toast in else which states no file selected
