### PR TITLE
Visual message when no data fetched in gyroscope

### LINKED ISSUE #1723: Logged Data not showing graph in Gyroscope when sensor absent
**Actual Behaviour**

When logged data is opened , it does not show the graph in devices with sensor absent.

**Expected Behaviour**

The graph should show either zero like when recorded or disable recording when sensor not present.

**Steps to reproduce it**

Open gyroscope with device not having the sensor and record some data and open it.

**LogCat for the issue**

Not Applicable

**Screenshots of the issue**

Screenshot_20190515-215301_PSLab

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by ho-dor**
Fixes #1723

**Changes**: Graphs removed and a visual message to user when no data fetched

**Screenshot/s for the changes**: 
Screenshot_20190610-231434_PSLab

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[gyro.zip](https://github.com/fossasia/pslab-android/files/3273178/gyro.zip)

### CODE REVIEW

**Comment by ho-dor** [comment]
@CloudyPadmal @neel1998 please check.

File: app/src/main/java/io/pslab/fragment/GyroscopeDataFragment.java [hunk 1]
```diff
@@ -114,9 +121,23 @@ public void onResume() {
...
             playRecordedData();
         } else if (gyroSensor.viewingData) {
-            recordedGyroArray = new ArrayList<>();
-            resetInstrumentData();
-            plotAllRecordedData();
+            if(sensorManager != null) {
+                recordedGyroArray = new ArrayList<>();
+                resetInstrumentData();
+                plotAllRecordedData();
+            }else{
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/fragment/GyroscopeDataFragment.java]: Reformat

File: app/src/main/java/io/pslab/fragment/GyroscopeDataFragment.java [hunk 2]
```diff
@@ -114,9 +121,23 @@ public void onResume() {
...
+
+                rootView.findViewById(R.id.gyroscope_x_axis_fragment).setVisibility(View.INVISIBLE);
+                rootView.findViewById(R.id.gyroscope_y_axis_fragment).setVisibility(View.INVISIBLE);
+                rootView.findViewById(R.id.gyroscope_z_axis_fragment).setVisibility(View.INVISIBLE);
+
+                noSensorText.setText(getResources().getString(R.string.no_data_recorded_gyro));
+                noSensorText.setAllCaps(true);
+                gyroLinearLayout.addView(noSensorText);
+
+
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/fragment/GyroscopeDataFragment.java]: reformat

File: app/src/main/java/io/pslab/fragment/GyroscopeDataFragment.java [hunk 3]
```diff
@@ -133,6 +154,8 @@ public void onDestroyView() {
         }
         if (sensorManager != null) {
             sensorManager.unregisterListener(gyroScopeSensorEventListener);
+        }else{
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/fragment/GyroscopeDataFragment.java]: reformat

File: app/src/main/res/values/strings.xml [hunk 4]
```diff
@@ -831,4 +831,5 @@
     <string name="setting_thermo_sensor_gain">setting_thermo_sensor_gain</string>
     <string name="default_value_thermo">0</string>
     <string name="thermo_default">°C</string>
+    <string name="no_data_recorded_gyro">No data recorded as the sensor is not present in the device. Try with an external sensor.</string>
```
Comment (CloudyPadmal) [inline app/src/main/res/values/strings.xml]: move to relevant section where variable related to gyro is

**Comment by ho-dor** [comment]
@CloudyPadmal done
