### PR TITLE
Fixes #448 : BJT Transfer Characteristics Experiment

### LINKED ISSUE #448: Implement BJT Transfer Characteristics Experiment
**Actual Behaviour**

BJT Transfer Characteristics experiment is not implemented

**Expected Behaviour**

BJT Transfer Characteristics experiment needs to be implemented in the saved experiments

**Steps to reproduce it**

1. Open app
2. Go to `Saved Experiments`
3. Check `BJT Transfer Characteristics` experiment in `BJTs and FETs`

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes issue #448 

Changes: 
- Added BJT Transfer characteristics experiment with calculations
- Broke down resource file creating into another issue #449 . So please note that this PR fixes only the experiment part and attached link to make the resource file available once it is merged! :)

Screenshots for the change: 

transfercharacteristics

APK for testing:

[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1204212/app-debug.apk.zip)

### CODE REVIEW

File: app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorTransferExperiment.java [hunk 1]
```diff
@@ -0,0 +1,253 @@
...
+        outputChart.invalidate();
+    }
+
+    private class CalcDataPoint extends AsyncTask<Float, Void, Void> {
+
+        @Override
+        protected Void doInBackground(Float... params) {
+            float voltage = params[0];
+            scienceLab.setPV2(voltage);
+            float collectorResistance = 1 * K;
```
Comment (asitava1998) [inline app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorTransferExperiment.java]: Why is it written like this?  1 * K.

Comment (CloudyPadmal) [inline app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorTransferExperiment.java]: I used `K` as a multiplier so this will be read as a 1K resistor! :)

**Comment by CloudyPadmal** [comment]
Thank you @viveksb007 :+1:
