### PR TITLE
fix: fixed the In-Built MIC to work properly after toggling the PSLab MIC

### LINKED ISSUE #2421: After toggling the PSLab MIC, the In-Built-MIC feature doesn't work, when the PSLab device isn't connected
This issue is a proper rephrase of #2173, since the problem isn't clearly stated there.
**Actual Behaviour**
If one first toggles the PSLab MIC, the In-Built-MIC feature doesn't work after that, regardless of whether it is toggled directly or after switching OFF the PSLab MIC. This happens only if the PSLab Device isn't connected.

**Expected Behaviour**
The In-Built-MIC feature should always work, regardless of the fact that the PSLab MIC feature has been used first or not. 

**Steps to reproduce it**
Ensure that the PSLab Device isn't connected.
1. Click on the PSLab MIC checkbox to toggle it.
2. Either turn OFF the PSLab MIC first and then click on the In-Built-MIC checkbox, or click on the In-Built-MIC checkbox directly.
3. One will observe that the feature isn't working.

**Screenshots of the issue**
This is a screenshot of the OscilloscopeActivity after following the above steps:-
Screenshot 2024-05-19 184502
One can observe that there is no plot for the Built-In-MIC input.

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by AsCress**
Fixes #2421 and #2173 
This issue was arising primarily due to the following two reasons:-

1. In the ChannelParametersFragment, whenever one checkbox was checked, the other was being unchecked without correcting the state of isAudioInputSelected, causing it to get toggled two times, resulting in it being false, even when one of the audio inputs was selected.
2. In the OscilloscopeActivity, the synchronized method was placed in the wrong scope, causing lock.wait() to get executed even when there was no PSLab Device connected. As there was no input, the thread would keep waiting forever, as lock.notify() would never be called. Hence, it would never detect a change in isAudioInputSelected.

## Changes 
- app/src/main/java/io/pslab/fragment/ChannelParametersFragment.java - corrected the state of isAudioInputSelected whenever a checkbox is checked, due to another getting unchecked.
- app/src/main/java/io/pslab/activity/OscilloscopeActivity.java - corrected the scope of the synchronized method, so that lock.wait() only gets executed if the PSLab Device is connected.

## Screenshots / Recordings  
This is a screenshot of the OscilloscopeActivity, after following the required steps to reproduce the issue, as mentioned in #2421.
WhatsApp Image 2024-05-19 at 6 29 45 PM
As one can see, the issue is resolved.

**Checklist**: 
- [x] **No hard coding**: I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard coding any value.
- [x] **No end of file edits**: No modifications done at end of resource files `strings.xml`, `dimens.xml` or `colors.xml`.
- [x] **Code reformatting**: I have reformatted code and fixed indentation in every file included in this pull request.
- [x] **No extra space**: My code does not contain any extra lines or extra spaces than the ones that are necessary.

### CODE REVIEW

File: app/src/main/java/io/pslab/fragment/ChannelParametersFragment.java [hunk 1]
```diff
@@ -10,6 +10,7 @@
 import androidx.core.content.ContextCompat;
 import androidx.fragment.app.Fragment;
 
+import android.util.Log;
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/fragment/ChannelParametersFragment.java]: Looks like this is unused?

Comment (AsCress) [reply app/src/main/java/io/pslab/fragment/ChannelParametersFragment.java]: Oh yes! My bad, I had added these for debugging. I'm removing them.

**Comment by AsCress** [comment]
@CloudyPadmal Done:)

**Comment by marcnause** [comment]
I have tested the app without the fix and with the fix. I was able to reproduce the problem and I can confirm that I can toggle between both MICs now and the build-in microphone works whenever it is selected in the version which contains the fix.

**Comment by marcnause** [comment]
@AsCress, just a general remark: I just noticed that you created this pull request on your development branch. I don't know if this was intentional or not. I like to (and sometimes forget to) make an extra branch for every issue I work on (named e.g. issue2421). That way I can switch between working on different issues. Even more convenient: Waiting for the merge of a pull request does not block me from working on other issues.

**Comment by AsCress** [comment]
> @AsCress, just a general remark: I just noticed that you created this pull request on your development branch. I don't know if this was intentional or not. I like to (and sometimes forget to) make an extra branch for every issue I work on (named e.g. issue2421). That way I can switch between working on different issues. Even more convenient: Waiting for the merge of a pull request does not block me from working on other issues.

@marcnause Thank you very much for testing the fix and your comments!! I'll surely make extra branches for different issues from now on.

**Review by CloudyPadmal — APPROVED** [review]
