### PR TITLE
Toast message in gas sensor made consistent with all instruments

### LINKED ISSUE #1979: Not Connected toast blinking continuously unlike any other instrument in gas sensor
**Actual Behaviour**

Toast should be shown once on opening instrument.

**Expected Behaviour**

Toast should be visible for short time.

**Steps to reproduce it**

Open Gas Sensor.

**LogCat for the issue**

N/A

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by ho-dor**
Fixes #1979 

**Changes**: Toast message made consistent with all other instruments.

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[toast.zip](https://github.com/fossasia/pslab-android/files/3678516/toast.zip)

### CODE REVIEW

File: app/src/main/java/io/pslab/fragment/GasSensorDataFragment.java [hunk 1]
```diff
@@ -83,6 +83,7 @@ public void onCreate(@Nullable Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
         startTime = System.currentTimeMillis();
         gasSensorActivity = (GasSensorActivity) getActivity();
+
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/fragment/GasSensorDataFragment.java]: Remove

File: app/src/main/java/io/pslab/fragment/GasSensorDataFragment.java [hunk 2]
```diff
@@ -91,6 +92,9 @@ public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup c
         rootView = inflater.inflate(R.layout.fragment_gas_sensor, container, false);
         unbinder = ButterKnife.bind(this, rootView);
         scienceLab = ScienceLabCommon.scienceLab;
+        if (!scienceLab.isConnected()){
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/fragment/GasSensorDataFragment.java]: Reformat the code

**Comment by ho-dor** [comment]
Any other issues with this @neel1998 @CloudyPadmal ?
