### PR TITLE
Fixes #579 : Servo Motors

### LINKED ISSUE #579: Implement Servo Motors Experiment
**Actual Behaviour**

Experiment related to servo motor functionality hasn't been implemented yet

**Expected Behaviour**

The experiment needs to be implemented in Add On modules experiments

**Steps to reproduce it**

1. Open app
2. Go to `Saved Experiment`
3. Open `Add on modules`
4. Select `Various Utilities`
5. Try `Servo Motors`

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes issue #579 

Changes: 
- Implemented layouts and functionality to perform servo motors related experiments

Screenshots for the change: 
servo

APK for testing:
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1246465/app-debug.apk.zip)

### CODE REVIEW

File: app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java [hunk 1]
```diff
@@ -17,6 +17,8 @@
 import org.fossasia.pslab.experimentsetup.DiodeExperiment;
 import org.fossasia.pslab.experimentsetup.NFETTransferCharacteristicsExperiment;
 import org.fossasia.pslab.experimentsetup.NonInvertingOpAmpExperiment;
+import org.fossasia.pslab.experimentsetup.ServoMotorsExperiment;
+import org.fossasia.pslab.experimentsetup.SummingJunctionExperiment;
```
Comment (viveksb007) [inline app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java]: `Summing Junction Experiment` is exported twice.

Comment (CloudyPadmal) [inline app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java]: Thanks for reviewing it @viveksb007 ! I removed one statement! :)
