### PR TITLE
Fixed #539 exported data in csv format

### LINKED ISSUE #539: export locally logged sensor data in csv format
**Actual Behaviour**

currently data is logged as text file

**Expected Behaviour**

data logging in csv format should also be supported to be used in data visualisation scripts, matlab, etc.

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by viveksb007**
Fixes issue #539 

Changes: 
- Support for exporting sensor data in csv format added. 
- Data would be exported in format selected in app settings (`txt`,`csv`)

Screenshots for the change: 
screenshot_2017-08-20-13-30-36-905_cn wps moffice_eng

### CODE REVIEW

File: app/src/main/java/org/fossasia/pslab/activity/ShowLoggedData.java [hunk 1]
```diff
@@ -1,14 +1,17 @@
...
 import android.os.Bundle;
 import android.os.Environment;
+import android.preference.PreferenceManager;
 import android.support.annotation.Nullable;
 import android.support.v7.app.AppCompatActivity;
 import android.support.v7.widget.DefaultItemAnimator;
 import android.support.v7.widget.LinearLayoutManager;
 import android.support.v7.widget.RecyclerView;
 import android.support.v7.widget.Toolbar;
+import android.util.Log;
```
Comment (CloudyPadmal) [inline app/src/main/java/org/fossasia/pslab/activity/ShowLoggedData.java]: Hi @viveksb007 ! The rest looks ok! :+1: Nice work! I guess this import is unused now! :)

Comment (viveksb007) [inline app/src/main/java/org/fossasia/pslab/activity/ShowLoggedData.java]: Must have left after debugging. Anyways it would be used for debugging as there is some work left in Data Sensor Logger Activity.
Thanks for the review.

Comment (CloudyPadmal) [inline app/src/main/java/org/fossasia/pslab/activity/ShowLoggedData.java]: Then it's ok! :+1:

**Comment by viveksb007** [comment]
@jithinbp I was thinking of putting limited to resolution but since because of byte read error, values aren't correct. So once byte read error is solved, would put limit to significant figures.
