### PR TITLE
"no log data" message visible upon deleting everything from logged data

### LINKED ISSUE #1570: No message appears after deleting all the logged data
**Actual Behaviour**
No message appears after deleting all the logged data

**Expected Behaviour**
After deleting all the data..A message should appear(no logged data)

**Steps to reproduce it**
1. Delete all logged data

**Screenshots of the issue**

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1570 

**Changes**: checking the size of log data, upon zero making the "no log data" message visible

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

### CODE REVIEW

**Comment by neel1998** [comment]
@CloudyPadmal  kindly review

File: app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java [hunk 1]
```diff
@@ -133,6 +133,12 @@ public void onClick(DialogInterface dialog, int whichButton) {
                         }
                         LocalDataLog.with().clearSensorBlock(block.getBlock());
                         dialog.dismiss();
+                        if (LocalDataLog.with().getAllSensorBlocks().size() <= 0){
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java]: Will the `size()` go below 0?

Comment (neel1998) [reply app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java]: I should not...I just used less than equal to make it fail safe

**Comment by neel1998** [comment]
@CloudyPadmal  kindly review and merge.
