### PR TITLE
logic analyzer bug fixed

### LINKED ISSUE #1825: Logic Analyser Not working as expected
**Actual Behaviour**
Currently logic analyser is giving weird outputs

**Expected Behaviour**
Logic analyser should give output similar to python library and conventional logic analyser

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1825

**Changes**: Logic analyzer giving proper output 

**Screenshot/s for the changes**:

**before

**after

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[la.zip](https://github.com/fossasia/pslab-android/files/3462472/la.zip)

### <i> Just a few lines change does make a difference :joy: </i>

### CODE REVIEW

File: app/src/main/java/io/pslab/fragment/LALogicLinesFragment.java [hunk 1]
```diff
@@ -1188,13 +1188,13 @@ protected Void doInBackground(ArrayList<String>... arrayLists) {
...
+                delayThread(1000);
                 holder1 = scienceLab.fetchLAChannel(channelNumber1, data);
-                delayThread(500);
+                delayThread(1000);
                 holder2 = scienceLab.fetchLAChannel(channelNumber2, data);
-                delayThread(500);
+                delayThread(1000);
                 holder3 = scienceLab.fetchLAChannel(channelNumber3, data);
-                delayThread(500);
+                delayThread(1000);
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/fragment/LALogicLinesFragment.java]: Are these delays (1000 from 500) necessary?

Comment (neel1998) [reply app/src/main/java/io/pslab/fragment/LALogicLinesFragment.java]: I checked with 500 .... Sometimes it fails to fetch data. I guess it is safe to keep 1000.
