### PR TITLE
fix: Oscilloscope function button grouping and color changes

### LINKED ISSUE #880: Redesign Oscilloscope UI
**Actual Behaviour**

Oscilloscope layout contains a left pane with buttons.

**Expected Behaviour**

The buttons should separate from each other and have more meaning and interactivity. The selected setting should be highlighted.  

**Steps to reproduce it**

Choose Oscilloscope in Instruments

**LogCat for the issue**

> None

**Screenshots of the issue**

screenshot_2018-05-17-07-11-21

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Vikum94**
Fixes #880 

Changes: The four buttons channel parameters, timebase and trigger, data analysis and xy plot are separated from each other and when selected, there is a color change in the text background  

Screenshots for the change: 

screenshot_2018-05-19-12-57-39

APK for testing: 

[app-debug.zip](https://github.com/fossasia/pslab-android/files/2019230/app-debug.zip)

### CODE REVIEW

File: app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java [hunk 1]
```diff
@@ -509,38 +510,62 @@ public void onClick(View v) {
...
                 replaceFragment(R.id.layout_dock_os2, xyPlotFragment, "XYPlotFragment");
+                clearTextBackgroundColor();
+                xyPlotTextView.setBackgroundColor(Color.parseColor("#c72c2c"));
                 break;
         }
     }
 
+    @SuppressLint("ResourceType")
+    private void clearTextBackgroundColor() {
+        channelParametersTextView.setBackgroundColor(Color.parseColor("#7A7A7A"));
```
Comment (CloudyPadmal) [inline app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java]: Hello @Vikum94 ! Wouldn't it be better to move the hardcoded colors to `colors.xml` and call from there?

Comment (Vikum94) [reply app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java]: Ok. I'll change it. Thanks

**Comment by Vikum94** [comment]
Please find the updated apk file here

[app-debug.zip](https://github.com/fossasia/pslab-android/files/2019361/app-debug.zip)
