### PR TITLE
WIP: Playback data from SD card feature added

### LINKED ISSUE #1690: Playback data from SD Card
**Actual Behaviour**

PSLab v6 has SD card feature to log recording from different instruments. These recording will be in raw values with no visualization.

**Expected Behaviour**

Android app needs to support a feature to let user play back these recorded data by importing them from SD card and display in a similar manner to logged data in current app.

**Steps to reproduce it**

> Not available

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

New contributors can take up this issue and discuss with me how to integrate with the firmware

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1690 

**Changes**: 

I have added an option in data logger activity where user can import the log stored as CSV on the SD card for the instrument selected by the user. 

**Currently I have implemented this feature for Barometer and Lux meter. Once the mentors approves these changes I will add the other instruments as well**

**Screenshot/s for the changes**: 

Following are the steps to import log in the application

**step 1**

Create a CSV file on the SD card or local storage with proper headers and required fields as per selected instrument. (Following is a CSV for Luxmeter)
Screenshot_20190416-025340

**step 2**

Open DataLogger Activity, go to import log menu and in the alert dialogg select appropriate device, once a device is selected user can browse through the phone storage and select a file to be imported.

Screenshot_20190416-025351

Screenshot_20190416-025355

**step 3**

Once the file is selected, if the format of CSV is as per the selected instrument, the log entry of that file can be seen in the lit, clicking on it will play the logged data as usual.

Screenshot_20190416-025409

**GIFs**

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[SD_card_playback.zip](https://github.com/fossasia/pslab-android/files/3082166/SD_card_playback.zip)

@CloudyPadmal  I have implemented this feature according to my understanding of the issue you filed. Kindly suggest any change you think must be required to successfully implement this feature

### CODE REVIEW

**Comment by neel1998** [comment]
@CloudyPadmal  kindly have a look at this PR. Thanks

File: app/src/main/java/io/pslab/activity/DataLoggerActivity.java [hunk 1]
```diff
@@ -1,21 +1,41 @@
...
 import android.support.v7.widget.Toolbar;
+import android.view.LayoutInflater;
+import android.view.Menu;
 import android.view.MenuItem;
 import android.view.View;
+import android.widget.RadioButton;
+import android.widget.RadioGroup;
 import android.widget.TextView;
+import android.widget.Toast;
+
```
Comment (abhinavraj23) [inline app/src/main/java/io/pslab/activity/DataLoggerActivity.java]: @neel1998 You can remove this one extra line

File: app/src/main/java/io/pslab/activity/DataLoggerActivity.java [hunk 2]
```diff
@@ -94,7 +118,127 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
+                while(line != null){
+                    if (i != 0) {
+                        String[] data = line.split(",");
+                        try {
+                            time += 1000;
+                            BaroData baroData = new BaroData(time, block, Float.valueOf(data[2]), Double.valueOf(data[3]), Double.valueOf(data[4]));
+                            realm.beginTransaction();
+                            realm.copyToRealm(baroData);
+                            realm.commitTransaction();
+                        }catch (Exception e) {
```
Comment (abhinavraj23) [inline app/src/main/java/io/pslab/activity/DataLoggerActivity.java]: @neel1998 Have you reformatted the code, I don't think so, it shouldn't be this way!

File: app/src/main/java/io/pslab/activity/DataLoggerActivity.java [hunk 3]
```diff
@@ -94,7 +118,127 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
+                            Toast.makeText(this, "File format does not match device log format", Toast.LENGTH_SHORT).show();
+                        }
+                    }
+                    else {
+                        block = System.currentTimeMillis();
```
Comment (abhinavraj23) [inline app/src/main/java/io/pslab/activity/DataLoggerActivity.java]: Same here, please reformat the code!

**Comment by abhinavraj23** [comment]
@neel1998 Also please try to keep the images of the screenshot small by using markdown code to set image size.

File: app/src/main/java/io/pslab/activity/DataLoggerActivity.java (hunk 2 above)
Comment (neel1998) [reply app/src/main/java/io/pslab/activity/DataLoggerActivity.java]: @abhinavraj23  can you please explain what do you mean by "reformatted"?

Comment (abhinavraj23) [reply app/src/main/java/io/pslab/activity/DataLoggerActivity.java]: @neel1998 In Android Studio you can automatically format your code. Please follow this link https://stackoverflow.com/questions/16580171/code-formatting-shortcut-in-android-studio

Comment (neel1998) [reply app/src/main/java/io/pslab/activity/DataLoggerActivity.java]: @abhinavraj23  Oh okay, thanks. I will make the changes

Comment (abhinavraj23) [reply app/src/main/java/io/pslab/activity/DataLoggerActivity.java]: @neel1998 What I meant to say was there should be a space between the bracket and the "catch" word, in Android studio you can automatically do these minor formatting!

Comment (neel1998) [reply app/src/main/java/io/pslab/activity/DataLoggerActivity.java]: @abhinavraj23  great. i will make the necessary changes.

**Comment by neel1998** [comment]
@abhinavraj23  @cweitat  @CloudyPadmal  kindly review

**Comment by neel1998** [comment]
@abhinavraj23  @CloudyPadmal  any updates on this PR?

File: app/src/main/res/values/strings.xml [hunk 4]
```diff
@@ -1116,5 +1116,6 @@
     <string name="no_data_fetched">No Data Fetched</string>
     <string name="recorder">Recorder</string>
     <string name="save_graph">Save Graph</string>
-
+    <string name="import_log_action">Import Log</string>
+    <string name="import_data_log_no_selection_error">Kindly select one of the devices</string>
```
Comment (CloudyPadmal) [inline app/src/main/res/values/strings.xml]: We don't add string resources at the end of this file. It will make a lot of merge conflicts. Please move them up where similar text can be found.

File: app/src/main/res/menu/activity_data_logger_menu.xml [hunk 5]
```diff
@@ -0,0 +1,9 @@
+<?xml version="1.0" encoding="utf-8"?>
+<menu xmlns:android="http://schemas.android.com/apk/res/android"
+    xmlns:app="http://schemas.android.com/apk/res-auto">
+    <item
+        android:title="@string/import_log_action"
+        android:id="@+id/action_import_log"
+        app:showAsAction="never"
```
Comment (CloudyPadmal) [inline app/src/main/res/menu/activity_data_logger_menu.xml]: Since there's only one menu item, let's keep it showing. Please remove this `never` part.

File: app/src/main/java/io/pslab/activity/DataLoggerActivity.java [hunk 6]
```diff
@@ -94,7 +120,125 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
+                    if (i != 0) {
+                        String[] data = line.split(",");
+                        try {
+                            time += 1000;
+                            LuxData luxData = new LuxData(time, block, Float.valueOf(data[2]), Double.valueOf(data[3]), Double.valueOf(data[4]));
+                            realm.beginTransaction();
+                            realm.copyToRealm(luxData);
+                            realm.commitTransaction();
+                        } catch (Exception e) {
+                            Toast.makeText(this, "File format does not match device log format", Toast.LENGTH_SHORT).show();
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/activity/DataLoggerActivity.java]: Use string resources without hardcoded strings.

File: app/src/main/res/layout/import_log_device_type_alert_layout.xml [hunk 7]
```diff
@@ -0,0 +1,39 @@
...
+    xmlns:android="http://schemas.android.com/apk/res/android"
+    android:layout_width="match_parent"
+    android:layout_height="match_parent">
+    <RadioGroup
+        android:id="@+id/import_log_device_radio_group"
+        android:layout_width="wrap_content"
+        android:layout_height="wrap_content"
+        android:layout_centerInParent="true"
+        android:padding="50dp"
+        >
```
Comment (CloudyPadmal) [inline app/src/main/res/layout/import_log_device_type_alert_layout.xml]: Bring these `>` next to the ending of last lines. Applies to all the tags in this file.

File: app/src/main/java/io/pslab/activity/DataLoggerActivity.java [hunk 8]
```diff
@@ -94,7 +120,125 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
+                    if (i != 0) {
+                        String[] data = line.split(",");
+                        try {
+                            time += 1000;
+                            BaroData baroData = new BaroData(time, block, Float.valueOf(data[2]), Double.valueOf(data[3]), Double.valueOf(data[4]));
+                            realm.beginTransaction();
+                            realm.copyToRealm(baroData);
+                            realm.commitTransaction();
+                        } catch (Exception e) {
+                            Toast.makeText(this, "File format does not match device log format", Toast.LENGTH_SHORT).show();
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/activity/DataLoggerActivity.java]: Hardcoded strings here

File: app/src/main/java/io/pslab/activity/DataLoggerActivity.java [hunk 9]
```diff
@@ -94,7 +120,125 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
+        return true;
+    }
+
+    private void importLog() {
+        AlertDialog alertDialog;
+        AlertDialog.Builder dialogBuilder = new AlertDialog.Builder(this);
+        LayoutInflater inflater = this.getLayoutInflater();
+        final View dialogView = inflater.inflate(R.layout.import_log_device_type_alert_layout, null);
+        dialogBuilder.setView(dialogView);
+        dialogBuilder.setPositiveButton("Select", new DialogInterface.OnClickListener() {
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/activity/DataLoggerActivity.java]: Hardcoded strings

File: app/src/main/java/io/pslab/activity/DataLoggerActivity.java [hunk 10]
```diff
@@ -94,7 +120,125 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
+            @Override
+            public void onClick(DialogInterface dialog, int which) {
+                RadioGroup votingAlgoRadioGroup = dialogView.findViewById(R.id.import_log_device_radio_group);
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/activity/DataLoggerActivity.java]: Why this name `votingAlgoRadioGroup`?

**Comment by neel1998** [comment]
@CloudyPadmal I have made changes you suggested. Kindly review the PR. Thanks

**Comment by neel1998** [comment]
@CloudyPadmal  kindly merge this

**Comment by CloudyPadmal** [comment]
When uploading screenshots, make sure they are about 300~400 px height.
