### PR TITLE
fix: rate app navigate back to FAQ

### LINKED ISSUE #2198: Bug in Rate App from navigation
**Actual Behaviour**

When you go to Rate App from the navigation drawer, and go back, the faq fragment opens instead of what ever was before.

**Expected Behaviour**

On clicking Rate App, and on going back from this, the app should open whatever fragment or activity was open before clicking on Rate App

**Steps to reproduce it**

1. Click on Rate App from the navigation drawer.
2. Go back.

**LogCat for the issue**

**Screenshots of the issue**

https://user-images.githubusercontent.com/52701183/111509010-4cd54980-8772-11eb-9d1f-7a846aa5f1d6.mp4

**Would you like to work on the issue?**

Yes, I would like to work on this

### PR DESCRIPTION
**Pull request by Abhinavtdk**
Fixes #2198 

**Changes**: 
Added a break statement for the case R.id.nav_rate in Main Activity, setUpNavigationView

**Screenshot/s for the changes**: 

https://user-images.githubusercontent.com/52701183/111511466-c706cd80-8774-11eb-87bb-8636b2276c57.mp4

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:

### CODE REVIEW

File: app/src/main/java/io/pslab/activity/MainActivity.java [hunk 1]
```diff
@@ -259,11 +259,12 @@ public boolean onNavigationItemSelected(@NonNull MenuItem item) {
                         navItemIndex = 5;
                         CURRENT_TAG = TAG_ABOUTUS;
                         break;
- 		    case R.id.nav_rate:
+ 		            case R.id.nav_rate:
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/activity/MainActivity.java:262]:
```suggestion
 		        case R.id.nav_rate:
```

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]
This is a fix that's needed. Thanks for the PR.

File: app/src/main/java/io/pslab/activity/MainActivity.java [hunk 2]
```diff
@@ -259,11 +259,12 @@ public boolean onNavigationItemSelected(@NonNull MenuItem item) {
                         navItemIndex = 5;
                         CURRENT_TAG = TAG_ABOUTUS;
                         break;
- 		    case R.id.nav_rate:
+ 		        case R.id.nav_rate:
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/activity/MainActivity.java:262]: Revert this indentation

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]

**Review by CloudyPadmal — APPROVED** [review]
