### PR TITLE
Fixes #455 added About Us screen

### LINKED ISSUE #455: Add About Us screen in App
**Actual Behaviour**

Currently About Us doesn't show any content.

**Expected Behaviour**

About Us should show information about Fossasia and Pocket Science and it projects. Links to website.

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by viveksb007**
Fixes issue #455 

Changes:
- Added About Us screen

P.S: I have attached a screen shot of complete page after scrolling down.

Screenshots for the change: 
screenshot_2017-08-08-17-34-54-436_org fossasia pslab

### CODE REVIEW

File: app/src/main/java/org/fossasia/pslab/activity/AboutUs.java [hunk 1]
```diff
@@ -17,7 +20,40 @@
...
-        ButterKnife.bind(this);
+        simulateDayNight(0);
+        View aboutPage = new AboutPage(this)
+                .isRTL(false)
+                .setImage(R.drawable.logo200x200)
+                .setDescription(getString(R.string.about_us_description))
+                .addGroup("Connect with us")
+                .addEmail("pslab-fossasia@googlegroups.com")
+                .addWebsite("http://pslab.fossasia.org/")
+                .addGitHub("fossasia")
```
Comment (CloudyPadmal) [inline app/src/main/java/org/fossasia/pslab/activity/AboutUs.java]: This is soo cool! Should we add links to repositories and other pages inside these brackets? :)

Comment (asitava1998) [inline app/src/main/java/org/fossasia/pslab/activity/AboutUs.java]: Good idea. I think you should add the link of repo.

Comment (viveksb007) [inline app/src/main/java/org/fossasia/pslab/activity/AboutUs.java]: I have added main pslab website. That is sufficient, adding repo link won't help much. User isn't likely to go through code on mobile and everything is linked from pslab site.
