### PR TITLE
refactor: solved bugs in voltage measurement and resistance

### LINKED ISSUE #1266: [Multimeter] Wrong Voltage Reading
**Actual Behaviour**

Voltage Reading is reading twice the expected amount
Example
- VDD reads ~7v
- VR+ reads ~12v
- V+ reads ~ 18v

**Expected Behaviour**

- VDD should read ~3.3v
- VR+ should read ~6v
- V+ should read ~ 10v

**Steps to reproduce it**

Measure Voltage using Multimeter

**Would you like to work on the issue?**

@abhinavraj23, can you work on this?

### PR DESCRIPTION
**Pull request by abhinavraj23**
Fixes #1266 #1277 

**Changes**: 
Corrected the bugs in voltage measurement which occurred due to merging of pr #1221.

**Screenshot/s for the changes**: 
Not applicable

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]
[app.apk.zip](https://github.com/fossasia/pslab-android/files/2216513/app.apk.zip)

### CODE REVIEW

File: app/src/main/java/org/fossasia/pslab/activity/MultimeterActivity.java [hunk 1]
```diff
@@ -223,8 +223,8 @@ public void onClick(View v) {
                         break;
                     default:
                         if (scienceLab.isConnected()) {
-                            saveAndSetData(String.valueOf(String.format(Locale.ENGLISH, "%.2f", scienceLab.getVoltage(knobMarker[knobState], 1))), getString(R.string.multimeter_voltage_unit));
-                        }
+                            Double voltage =(scienceLab.getVoltage(knobMarker[knobState],1))/2;
```
Comment (CloudyPadmal) [inline app/src/main/java/org/fossasia/pslab/activity/MultimeterActivity.java]: @abhinavraj23 can you give this file a little reformatting. Then this will be good to merge!

**Comment by woshikie** [comment]
Working as intended

**Comment by abhinavraj23** [comment]
@CloudyPadmal @woshikie @harsh-2711 @Avjeet Changes done , please review :+1:

**Comment by abhinavraj23** [comment]
@woshikie In this pr the issues coming in resistance measurement is also solved :+1:
