### PR TITLE
fix: added default value to multimeter

### LINKED ISSUE #1530: Multimeter should show a default value of 0.00
**Actual Behaviour**

Currently, the multimeter shows blank by default

**Expected Behaviour**

It should show a default value of 0.00

**Steps to reproduce it**

Go to Multimeter Activity

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by abhinavraj23**
Fixes #1530 

**Changes**: 

Added default value of 0.00 to the multimeter

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/2753487/app-debug.apk.zip)

### CODE REVIEW

**Comment by cweitat** [comment]
Is there any other ways to show the default values? The decimal here uses dots but some countries uses commas.

File: app/src/main/java/io/pslab/activity/MultimeterActivity.java [hunk 1]
```diff
@@ -133,7 +134,7 @@ public void onClick(View v) {
         Typeface tf = Typeface.createFromAsset(getAssets(), "fonts/digital-7 (italic).ttf");
         quantity.setTypeface(tf);
 
-        String text_quantity = multimeter_data.getString("TextBox", null);
+        String text_quantity = multimeter_data.getString("TextBox", defaultValue);
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/activity/MultimeterActivity.java]: May be this can be stringformatted with English Locale to fix the comma dot issue rather than directly using the value.
