### PR TITLE
fix: Solved the bug in setting mode for Single Channel in Logic Analyzer

### LINKED ISSUE #1160: Mode of channel isn't properly set in Single Channel Mode in Logic Analyzer
**Actual Behaviour**

The mode i.e. edge option isn't properly set for Single Channel Mode in Logic Analyzer instrument

**Expected Behaviour**

The mode should be properly set

**Steps to reproduce it**

Go to `LALogicLinesFragment` class and then analyze `CaptureOne` sub-class

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

Not applicable

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by harsh-2711**
Fixes #1160 

**Changes**: Solved the bug in setting mode for Single Channel in Logic Analyzer

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:  
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2150486/app-debug.zip)

### CODE REVIEW

File: app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java [hunk 1]
```diff
@@ -595,45 +595,52 @@ public void onSlide(@NonNull View bottomSheet, float slideOffset) {
...
                     case "DISABLED":
                         digitalChannel.mode = DISABLED;
+                        mode = DISABLED;
                         break;
                     default:
                         digitalChannel.mode = EVERY_EDGE;
+                        mode = EVERY_EDGE;
                 }
+
+                scienceLab.startOneChannelLA(params[0], mode, params[0], 3);
```
Comment (Vikum94) [inline app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java]: Can't you use digitalChannel.mode instead of this different mode varibale?

**Comment by harsh-2711** [comment]
@Vikum94 Good suggestion.

**Comment by harsh-2711** [comment]
@Vikum94 Changes done.

**Comment by Vikum94** [comment]
> The mode i.e. edge option isn't properly set for Single Channel Mode in Logic Analyzer instrument
@harsh-2711 What do you mean by that and how is it fixed? I'm sorry for asking this, I didn't quite get that part.

**Comment by harsh-2711** [comment]
@Vikum94 The thing is that when I use the function startOneChannelLA(), there is an attribute of mode which needs to be set to get accurate results. In present situation, the mode is set after starting the Logic Analyzer to plot the graph.

File: app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java [hunk 2]
```diff
@@ -634,6 +618,23 @@ protected Void doInBackground(String... params) {
                     default:
                         digitalChannel.mode = EVERY_EDGE;
                 }
+
+                scienceLab.startOneChannelLA(params[0], digitalChannel.mode, params[0], 3);
+
```
Comment (abhinavraj23) [inline app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java]: @harsh-2711 nice work :+1: Just avoid this extra line  and all okay :+1:

Comment (harsh-2711) [reply app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java]: @abhinavraj23 The space is to differentiate the setup with the main method of starting the Logic Analyzer. It's same in all the four modes.
