### PR TITLE
about facebook/ twitter page links changed

### LINKED ISSUE #1864: Twitter and Facebook links not working in About screen
**Actual Behaviour**
Twitter and Facebook links not working in About screen

**Expected Behaviour**
Links should direct to respective pages

**Steps to reproduce it**
Click on facebook/twitter links in About page

**Screenshots of the issue**

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1864 

**Changes**:Correct links added

**Screenshot/s for the changes**:

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[about_links.zip](https://github.com/fossasia/pslab-android/files/3383500/about_links.zip)

### CODE REVIEW

File: app/src/main/java/io/pslab/fragment/AboutUsFragment.java [hunk 1]
```diff
@@ -48,8 +48,8 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container,
                 .addEmail("pslab-fossasia@googlegroups.com")
                 .addWebsite("http://pslab.fossasia.org/")
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/fragment/AboutUsFragment.java]: Update

**Comment by CloudyPadmal** [comment]
Why adding prs for milestones? Don't add them

**Comment by neel1998** [comment]
> Why adding prs for milestones? Don't add them

Sorry. My bad.
