### PR TITLE
fixes #627 add double tap to exit

### LINKED ISSUE #627: On a single back press I came out of the app
**Actual Behaviour**

When we are on the home fragment and press the back button,we exit the app.

**Expected Behaviour**

There should be a toast message like press back again to close.

**Steps to reproduce it**

Open the app and press the back button

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by nikit19**
Fixes issue #627 

Changes: added double tap to exit

Screenshots for the change: 
ezgif com-video-to-gif 2

### CODE REVIEW

File: app/src/main/java/org/fossasia/pslab/activity/MainActivity.java [hunk 1]
```diff
@@ -252,6 +255,7 @@ private void loadNavHeader() {
 
     @Override
     public void onBackPressed() {
+              Fragment fragment = getSupportFragmentManager().findFragmentById(R.id.frame);
```
Comment (viveksb007) [inline app/src/main/java/org/fossasia/pslab/activity/MainActivity.java]: reformat the code.

Comment (nikit19) [reply app/src/main/java/org/fossasia/pslab/activity/MainActivity.java]: @viveksb007 is it fine now?
