### PR TITLE
fix: Added support for all pins in Singe Channel Mode for Logic Analyzer

### LINKED ISSUE #1135: Logic Analyzer pins ID2, ID3 and ID4 not being activated
**Actual Behaviour**

On starting the Logic Analyzer by using the functions startTwoChannelLA, startThreeChannelLA.. available in Science Lab class, only ID1 is activated i.e available for fetching data. Rest all aren't activated and so generates no data.

**Expected Behaviour**

All the pins should generate data.

**Steps to reproduce it**

Go to Logic Analyzer and try all Logic Analyzer pins except ID1.

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

Not applicable

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by harsh-2711**
Fixes #1135  #1045 

**Changes**: All the pins are being activated and currently all are fetching data for Single Channel Mode in Logic Analyzer

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:  
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2135949/app-debug.zip)

### CODE REVIEW

**Comment by harsh-2711** [comment]
@CloudyPadmal @abhinavraj23 @Avjeet @Vikum94 Please review.

File: app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java [hunk 1]
```diff
@@ -2007,28 +2007,24 @@ public boolean fetchLAChannels() {
...
 
         LinkedHashMap<String, Integer> tempMap = new LinkedHashMap<>();
-        tempMap.put("ID1", initialStates.get("ID1"));
-        tempMap.put("ID2", initialStates.get("ID2"));
-        tempMap.put("ID3", initialStates.get("ID3"));
-        tempMap.put("ID4", initialStates.get("ID4"));
+        tempMap.put("ID1", initialStates.get("A"));
+        tempMap.put("ID2", initialStates.get("B"));
+        tempMap.put("ID3", initialStates.get("C"));
+        tempMap.put("ID4", initialStates.get("D"));
```
Comment (CloudyPadmal) [inline app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java]: Can't we use IDs instead of Letters here?

**Comment by harsh-2711** [comment]
@CloudyPadmal Changes done.
