### PR TITLE
Fixes #239 adds scienceLab methods to Advanced & Main section of control UI

### LINKED ISSUE #239: Implement scienceLab methods in Advanced section of Control
**Actual Behaviour**

As of now, scienceLab methods have not been implemented in Advanced Section of Control. They need to be implemented.

**Expected Behaviour**

The user will be able to use the Arbitrary Waveform generator, Pulse Width Modulation Configuration and Digital Output.

**Steps to reproduce it**

Application -> Control -> Advanced -> Click on any `SET` button or Checkbox.

**LogCat for the issue**

None.

**Screenshots of the issue**

None. 

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by asitava1998**
Fixes issue #239 

Changes: 
* Added scienceLab methods to Read & Advanced section of Control. The part of the code which causes errors has been commented as of now and I am looking into it.
* Changes datatype of frequency to `double` in scienceLab.

Screenshots for the change:

### CODE REVIEW

**Comment by akarshan96** [comment]
@asitava1998 can you provide the apk.
Thanks

**Comment by asitava1998** [comment]
@akarshan96  @viveksb007 @CloudyPadmal  Here is the [apk](https://drive.google.com/file/d/0B3F6wGD_1dcZVGp4VXQ4OG5ZaWc/view?usp=sharing) link for the testing.

File: app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentAdvanced.java [hunk 1]
```diff
@@ -83,6 +85,85 @@ public void onClick(View v) {
         etwidgetControlAdvanced10.init(getContext(), 0.1, 0.0, 1.0);
         etwidgetControlAdvanced11.init(getContext(), 1.0, 0.0, 360.0);
 
+        buttonControlAdvanced1.setOnClickListener(new View.OnClickListener() {
+            @Override
+            public void onClick(View v) {
```
Comment (viveksb007) [inline app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentAdvanced.java]: catch ```NumberFormatException``` here And check for ```sciencelab.isConnected && "SINE".equals(wavetypeW1)``` before calling scienceLab methods. Always use ```"string".equal()``` to avoid null exception.

File: app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentRead.java [hunk 2]
```diff
@@ -81,24 +81,24 @@ public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
         buttonControlRead1.setOnClickListener(new View.OnClickListener() {
             @Override
             public void onClick(View view) {
-                /*double resistance = scienceLab.getResistance();
-                tvControlRead1.setText(String.valueOf(resistance));*/
+                double resistance = scienceLab.getResistance();
```
Comment (viveksb007) [inline app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentRead.java]: same ```sciencelab.isConnected()``` check here and all other such places where sciencelab methods are accessed.

File: app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentAdvanced.java (hunk 1 above)
Comment (asitava1998) [inline app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentAdvanced.java]: I changed the string comparison part. Are you sure of `NumberFormatRestriction`, we already restricted the text to numbers and moreover Android Studio itself highlights the exceptions like these if they occur?

Comment (viveksb007) [inline app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentAdvanced.java]: ```NumberFormatException``` what if string given to Double.valueOf isn't decodeable as a double. [this exception](https://github.com/fossasia/pslab-android/blob/master/app/src/main/java/org/fossasia/pslab/adapters/ControlMainAdapter.java#L114), Android Studio doesn't tell about all possible errors.

**Comment by asitava1998** [comment]
@akarshan96 @viveksb007 @jithinbp @CloudyPadmal  Here is the updated [apk](https://drive.google.com/file/d/0B3F6wGD_1dcZcnNGZWFyd0dEYkU/view?usp=sharing). The `Read` portion of Control is now fully functional. The `Advanced` portion is also complete, just some testing remains.

**Comment by jithinbp** [comment]
:+1:
There's still some issue with the app icon though .  I could see the
conical flask logo in the installation dialog, but on the home screen it's
just a black box.

**Comment by asitava1998** [comment]
@akarshan96 @viveksb007 @jithinbp @CloudyPadmal  Here is the updated [apk](https://drive.google.com/file/d/0B3F6wGD_1dcZQTdNUnlITjlfWlE/view?usp=sharing). The `Read` and `Advanced` sections are complete. The `Read` section has been tested as well and currently I am testing the `Advanced` section.

**Comment by viveksb007** [comment]
@asitava1998 How did you tested read section?
Did you read some voltage or resistance between channel?

**Comment by asitava1998** [comment]
@viveksb007  For the voltage parts, I just it with a DC source. Connected the channels to it. For resistance, just made a simple circuit and connect `CH` & `GND` to get the value. For frequency, just used a function generator.

**Comment by asitava1998** [comment]
@viveksb007  I think this PR can be merged.  Whether the functionalities give the correct values or not can be tested after the other issues related to calibration data are fixed.
Pending PRs are also leading to merge conflicts and I have already made changes you requested.

**Comment by viveksb007** [comment]
@asitava1998 Okay but resolve the conflicts first. Please
