### PR TITLE
Fix #1794 validation added to robotic arm edit box

### LINKED ISSUE #1794: Robotic arm doesn't validate values
**Actual Behaviour**

In robotic arm, we can enter numbers bigger than 360

**Expected Behaviour**

Since it's degrees, have to limit within 0-360

**Steps to reproduce it**

Try entering numbers bigger than 360 in text boxes

**LogCat for the issue**

> Not available

**Screenshots of the issue**

**Would you like to work on the issue?**

Issue for GSoC

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1794 

**Changes**: 
Validation added to robotic arm servo edit box so user can enter values only in range of 0 - 360

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[robotic_arm_valid_values.zip](https://github.com/fossasia/pslab-android/files/3285225/robotic_arm_valid_values.zip)

### CODE REVIEW

**Comment by neel1998** [comment]
@CloudyPadmal  @ho-dor  @cweitat  please review

File: app/src/main/java/io/pslab/activity/RoboticArmActivity.java [hunk 1]
```diff
@@ -339,8 +358,14 @@ public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
                 removeStatusBar();
                 if (actionId == EditorInfo.IME_ACTION_DONE) {
                     degree = Integer.valueOf(degreeText4.getText().toString());
-                    seekArc4.setProgress((int) (degree / 3.6));
-                    editEnter = true;
+                    if (degree > 360 || degree < 0) {
+                        degreeText4.setText(getResources().getString(R.string.zero));
+                        seekArc4.setProgress(0);
```
Comment (ho-dor) [inline app/src/main/java/io/pslab/activity/RoboticArmActivity.java]: It does not impact the working but degreeText1, 2, 3 ,4 should be used respectively , right now there is degreeText4 for all 4 servo layouts.

Comment (neel1998) [reply app/src/main/java/io/pslab/activity/RoboticArmActivity.java]: done. Thanks for pointing out
