### PR TITLE
Fixes #474 : Capacitor Discharge experiment

### LINKED ISSUE #474: Implement Capacitor Discharging experiment
**Actual Behaviour**

Current saved experiments do not implement capacitor discharging experiment

**Expected Behaviour**

Capacitor Discharge Experiment needs to be implemented in the saved experiments under School Level experiments

**Steps to reproduce it**

1. Open app
2. Go to `Saved Experiments`
3. Check `School Level` experiments

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes issue #474 

Changes: 
- Implemented Capacitor Discharge experiment as in [this](https://github.com/fossasia/pslab-desktop-apps/blob/development/psl_res/GUI/Z_SCHOOL_LEVEL/A_voltage_fundamentals/L_CAPACITOR_DISCHARGE.py) in desktop application
- Added two buttons to charge the capacitor and discharge the capacitor. Once discharge is clicked, data will be logged to plot the discharging curve

Screenshots for the change: 
fix

APK for testing:
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1215705/app-debug.apk.zip)

> There seem to be an error in voltage readings as it always converge to a value around `8.260`. Can you guys give this PR a look to see if there's any potential error? Thanks a lot! :)

### CODE REVIEW

File: app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java [hunk 1]
```diff
@@ -112,6 +115,9 @@ public Fragment getItem(int position) {
                 if (experimentTitle.equals(context.getString(R.string.nfet_output_characteristics)))
                     return NFETOutputCharacteristicsExperiment.newInstance();
                 if (experimentTitle.equals("Half Wave Rectifier"))
+                    return RectifierExperiment.newInstance();
```
Comment (viveksb007) [inline app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java]: It should be ```return RectifierExperiment.newInstance("Half Wave Rectifier");```.

Comment (CloudyPadmal) [inline app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java]: Ah thanks for the review @viveksb007 It must have happened when resolving conflicts! I made the changes!
