### PR TITLE
Java docs added to ScienceLab class

### LINKED ISSUE #1833: Add JavaDocs to ScienceLab.java class
**Actual Behaviour**

[`ScienceLab.java`](https://github.com/fossasia/pslab-android/blob/development/app/src/main/java/io/pslab/communication/ScienceLab.java) class got no documentation.

**Expected Behaviour**

Each function should be well documented with JavaDocs so that it will be helpful for new developers to understand the code

**Steps to reproduce it**

Check out [`ScienceLab.java`](https://github.com/fossasia/pslab-android/blob/development/app/src/main/java/io/pslab/communication/ScienceLab.java)  class

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

@neel1998 and @ho-dor , I suggest you resolve this issue as part by part. Whenever you are using a function in ScienceLab class, read through that function well and add JavaDocs to that specific function. Let's progress through that way.

### PR DESCRIPTION
**Pull request by ho-dor**
Fixes #1833 

**Changes**: Added docs for few more methods. No clash with #1834 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

### CODE REVIEW

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 1]
```diff
@@ -1879,6 +1879,23 @@ public void startOneChannelLABackup(Integer trigger, String channel, Integer max
...
+                        - EVERY_RISING_EDGE           = 3
+                        - EVERY_FALLING_EDGE          = 2
+                        - EVERY_EDGE                  = 1
+                        - DISABLED                    = 0
+     * @param triggerChannel ['ID1','ID2','ID3','ID4','SEN','EXT','CNTR']
+     * @param triggerMode    1=Falling edge
+                             0=Rising Edge
+                            -1=Disable Trigger
+     */
+
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: Let's remove these extra line breaks everywhere in the PR and make it looks uniform

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 2]
```diff
@@ -2127,10 +2185,11 @@ public void startFourChannelLA(Integer trigger, Double maximumTime, ArrayList<In
         return null;
     }
 
+    /**
+     * Stop any running logic analyzer function.
+     */
+
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: @ho-dor can we get these changes addressed soon? Will take about 5 minutes

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 3]
```diff
@@ -2411,12 +2512,12 @@ public Double capacitanceViaRCDischarge() {
         return null;
     }
 
+    /**
+     * Charges a capacitor connected to IN1 via a 20K resistor from a 3.3V source for a fixed interval
+     * @return the capacitance calculated using the formula Vc = Vs(1-exp(-t/RC))
+     */
+
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: Here

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 4]
```diff
@@ -2393,6 +2488,12 @@ public Double capacitanceViaRCDischarge() {
         }
     }
 
+    /**
+     * Charges a capacitor connected to IN1 via a 20K resistor from a 3.3V source for a fixed interval.
+     * @param cTime range of time
+     * @return the capacitance calculated using the formula Vc = Vs(1-exp(-t/RC))
+     */
+
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: here

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 5]
```diff
@@ -2337,6 +2427,11 @@ public void countPulses(String channel) {
         }
     }
 
+    /**
+     * Read pulses counted using a digital input. Call countPulses before using this.
+     * @return number of pulse.
+     */
+
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: here

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 6]
```diff
@@ -2325,6 +2410,11 @@ public void setState(Map<String, Integer> args) {
 
     }
 
+    /**
+     * Count pulses on a digital input. Retrieve total pulses using readPulseCount.
+     * @param channel The input pin to measure rising edges on : ['ID1','ID2','ID3','ID4','RES','EXT','CNTR']
+     */
+
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: here

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 7]
```diff
@@ -2296,10 +2367,24 @@ public DigitalChannel getDigitalChannel(int i) {
...
     public Boolean getState(String inputID) {
         return this.getStates().get(inputID);
     }
 
+    /**
+     * set the logic level on digital outputs SQR1,SQR2,SQR3,SQR4.
+     * @param args SQR1,SQR2,SQR3,SQR4
+            states(0 or 1)
+     */
+
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: here

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 8]
```diff
@@ -2296,10 +2367,24 @@ public DigitalChannel getDigitalChannel(int i) {
...
     }
 
+    /**
+     * Fetch the state of given input ID.
+     * @param inputID the input channel
+                        'ID1' -> state of ID1
+                        'ID4' -> state of ID4
+     * @return the logic level on the specified input (ID1,ID2,ID3, or ID4)
+     */
+
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: here

File: app/src/main/java/io/pslab/communication/ScienceLab.java [hunk 9]
```diff
@@ -2278,6 +2344,11 @@ public DigitalChannel getDigitalChannel(int i) {
         return dChannels.get(i);
     }
 
+    /**
+     * Gets the state of the digital inputs.
+     * @return dictionary with keys 'ID1','ID2','ID3','ID4'.
+     */
+
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/communication/ScienceLab.java]: here
