### PR TITLE
fix: updating "Delete All Data" operation

### LINKED ISSUE #2184: "Delete All Data" button doing nothing after all logs are deleted.
**Actual Behaviour**

After individual deletion of the logs the "Delete All Data" menu item still shows a Dialog Box to delete a log and then doesn't print anything.

**Expected Behaviour**

The "Delete All Data" items menu should toast a message "Nothing To Delete" when there is no data to delete.

**Steps to reproduce it**

Go to any device. Create a data log and open the logged data activity. Delete all the data logs one by one and then click on "Delete All Data" items menu.

**Screenrecording of the issue**

https://user-images.githubusercontent.com/65716045/105617850-b8043e80-5e07-11eb-9fd6-0989a89e7859.mp4

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by KushMehta1511**
The code has been modified to check whether any log is present while deleting and if no logs are present then the "Delete All Data" menu option shows a snackbar "Nothing To Delete".

Fixes #2184 

**Changes**: 
In the onOptionsItemSelected function under the category of R.id.delete_all an if condition is added to check whether the size of LocalDataLog is greater than 0 or not. If it is 0 then the "Delete All Data" displays a snackbar "Nothing to delete", otherwise functions normally as before.

**Screenshot/s for the changes**: 
Before: 

https://user-images.githubusercontent.com/65716045/105618271-6198ff00-5e0b-11eb-9801-90825859383b.mp4

After:
Nothing to Delete

**Checklist**: 
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 

[app-fdroid-debug.zip](https://github.com/fossasia/pslab-android/files/5861389/app-fdroid-debug.zip)

### CODE REVIEW

File: app/src/main/java/io/pslab/activity/DataLoggerActivity.java [hunk 1]
```diff
@@ -174,20 +174,26 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
-                            public void onClick(DialogInterface dialog, int which) {
-                                deleteAllProgressBar.setVisibility(View.VISIBLE);
-                                new DeleteAllTask().execute();
-                            }
-                        }).setNegativeButton(context.getString(R.string.cancel), new DialogInterface.OnClickListener() {
-                    public void onClick(DialogInterface dialog, int which) {
-                        dialog.dismiss();
-                    }
-                }).create().show();
+                if(LocalDataLog.with().getAllSensorBlocks().size() <= 0){
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/activity/DataLoggerActivity.java:177]:
```suggestion
                if (LocalDataLog.with().getAllSensorBlocks().size() == 0) {
```

File: app/src/main/java/io/pslab/activity/DataLoggerActivity.java [hunk 2]
```diff
@@ -174,20 +174,26 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
+                    CustomSnackBar.showSnackBar(findViewById(android.R.id.content), context.getString(R.string.nothing_to_delete),
+                            null, null, Snackbar.LENGTH_SHORT);
+                    new DeleteAllTask().execute();
+                } else{
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/activity/DataLoggerActivity.java:181]:
```suggestion
                } else {
```

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]

**Review by CloudyPadmal — APPROVED** [review]
