### PR TITLE
fix: Handled back button press in Webview of Home Fragment

### LINKED ISSUE #947: Back button directly redirecting to Home page
**Actual Behaviour**

The back button closes the webview (although links are opened) and redirects to Home fragment

**Expected Behaviour**

On pressing back button, webview should go one page back if any or should then close the webview

**Steps to reproduce it**

Go to Devices tab and navigate the "What is PSLab Device?" link

**LogCat for the issue**

Not applicable

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by harsh-2711**
Fixes #947 

Changes: Changed the onKeyListner for WebView so that it go backs a page if any or closes the WebView when back button is pressed

Screenshots for the change: 

APK for testing: 
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2060377/app-debug.zip)

NOTE: All the changes in the declarations and the import statements are due to code reformatting

### CODE REVIEW

**Comment by harsh-2711** [comment]
@Avjeet  But restricting to one page isn't a great idea because the user won't be able to click the provided links on the home page as so it will give a bad user experience. So it is better to handle the back button press.

File: app/src/main/java/org/fossasia/pslab/fragment/HomeFragment.java [hunk 1]
```diff
@@ -116,6 +120,24 @@ public void onPageFinished(WebView view, String url) {
...
+                if (event.getAction() == KeyEvent.ACTION_DOWN) {
+                    WebView webView = (WebView) v;
+                    switch (keyCode) {
+                        case KeyEvent.KEYCODE_BACK:
+                            if (webView.canGoBack()) {
+                                webView.goBack();
+                                return true;
+                            }
+                            break;
+                    }
```
Comment (Vikum94) [inline app/src/main/java/org/fossasia/pslab/fragment/HomeFragment.java]: add the default case also. Otherwise it shows in codacy as a bad pr.

**Comment by harsh-2711** [comment]
@Vikum94  Changes done.

**Comment by Avjeet** [comment]
Code looks okay could u provide with the apk.

**Comment by mariobehling** [comment]
Please provide apk in future.
