### PR TITLE
fix: Solved the issue of app crash while pressing Autoscan button in Sensors instrument

### LINKED ISSUE #1215: App crashes on pressing AutoScan button in sensors instrument
**Actual Behaviour**

The app crashes on pressing AutoScan button in `Sensors` instrument when the device is connected.

**Expected Behaviour**

The app shouldn't crash

**Steps to reproduce it**

Go to `Sensors` -> Press AutoScan button

**LogCat for the issue**

FATAL EXCEPTION: Thread-3
                  Process: org.fossasia.pslab, PID: 9570
                  android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                      at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7913)
                      at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1299)
                      at android.view.View.requestLayout(View.java:22178)
                      at android.view.View.requestLayout(View.java:22178)
                      at android.view.View.requestLayout(View.java:22178)
                      at android.view.View.requestLayout(View.java:22178)
                      at android.view.View.requestLayout(View.java:22178)
                      at android.view.View.requestLayout(View.java:22178)
                      at android.view.View.requestLayout(View.java:22178)
                      at android.view.View.requestLayout(View.java:22178)
                      at android.support.v4.widget.NestedScrollView.requestLayout(NestedScrollView.java:1669)
                      at android.view.View.requestLayout(View.java:22178)
                      at android.widget.TextView.checkForRelayout(TextView.java:8559)
                      at android.widget.TextView.setText(TextView.java:5427)
                      at android.widget.TextView.setText(TextView.java:5283)
                      at android.widget.TextView.setText(TextView.java:5240)
                      at org.fossasia.pslab.activity.SensorActivity.populateSensors(SensorActivity.java:148)
                      at org.fossasia.pslab.activity.SensorActivity.access$100(SensorActivity.java:41)
                      at org.fossasia.pslab.activity.SensorActivity$1.run(SensorActivity.java:57)
                      at java.lang.Thread.run(Thread.java:764)

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by harsh-2711**
Fixes #1215 

**Changes**: Made use of AsyncTask to run a thread in the background and to set the text in the text view which wasn't possible to set from a three-level running thread

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2187616/app-debug.zip)

### CODE REVIEW

**Comment by harsh-2711** [comment]
@CloudyPadmal @abhinavraj23 @Avjeet @Vikum94 @woshikie @cweitat Please review.

**Comment by harsh-2711** [comment]
@woshikie Changes done. Please review it.

File: app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java [hunk 1]
```diff
@@ -140,43 +142,49 @@ public void onItemClick(AdapterView<?> parent, View view, int position, long id)
...
-        }
+            for (int key : sensorAddr.keySet()) {
+                dataName.add(sensorAddr.get(key));
+            }
 
-        for (int key : sensorAddr.keySet()) {
-            dataName.add(sensorAddr.get(key));
+            tvSensorScan.setText(tvData);
+            adapter.notifyDataSetChanged();
+            buttonSensorAutoScan.setClickable(true);
```
Comment (woshikie) [inline app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java]: Please move setClickable(true) to a place where it will always run. There could be cases where sensorAddr.keySet() could return an empty array and therefore not run setClickable(true). Which then user will be stuck without a button to click

Comment (woshikie) [reply app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java]: It is also not best practice to set clickable in a loop as it takes up iterations doing the same thing again and again, possibly slowing down the program, or in this case, android app

Comment (harsh-2711) [reply app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java]: @woshikie I  forgot to remove the loop. It is of no use. We can directly use the PopulateSensors class to process thread in the background. So, I have removed the loop and you can now review it.

File: app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java [hunk 2]
```diff
@@ -140,43 +131,49 @@ public void onItemClick(AdapterView<?> parent, View view, int position, long id)
...
         }
```
Comment (woshikie) [inline app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java]: Did you forget to remove this line as well? It might cause compilation error

Comment (harsh-2711) [reply app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java]: Why should '}' cause compilation error? It is the ending bracket of onPostExecute() method.

Comment (woshikie) [reply app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java]: My bad. It looks like the closing bracket for the for loop instead of the function.
