### PR TITLE
Fix #1759 multimeter record bug fixed

### LINKED ISSUE #1759: App crashes on clicking export data option of multimeter
**Actual Behaviour**
App crashes on clicking export data option of multimeter

**Expected Behaviour**
App should not crash and a log file should be created

**Steps to reproduce it**
1. Record data in multimeter
2. Pause and select export data option

**LogCat for the issue**
2019-05-31 12:45:57.070 23742-23742/io.pslab E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.pslab, PID: 23742
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
        at io.pslab.others.CSVLogger.writeCSVFile(CSVLogger.java:83)
        at io.pslab.activity.MultimeterActivity.onOptionsItemSelected(MultimeterActivity.java:428)
        at android.app.Activity.onMenuItemSelected(Activity.java:3469)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:436)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:196)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
        at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:204)
        at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1158)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3153)
        at android.widget.AbsListView$3.run(AbsListView.java:4068)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Screenshots of the issue**

**Would you like to work on the issue?**
yes

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1759 

**Changes**: Bug fixed, pause button replaced with stop button, csv file created on clicking stop button.

**Screenshot/s for the changes**:

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[multimeter_log.zip](https://github.com/fossasia/pslab-android/files/3241434/multimeter_log.zip)

@CloudyPadmal  kindly review

### CODE REVIEW

**Comment by neel1998** [comment]
@CloudyPadmal  it would be great if you can merge this so that i can start working on #1762

File: app/src/main/java/io/pslab/activity/MultimeterActivity.java [hunk 1]
```diff
@@ -406,52 +406,50 @@ public boolean onOptionsItemSelected(MenuItem item) {
                     if (recordData) {
                         item.setIcon(R.drawable.ic_record_white);
                         recordData = false;
-                        CustomSnackBar.showSnackBar(coordinatorLayout, getString(R.string.data_recording_paused), null, null, Snackbar.LENGTH_LONG);
+                        if (isDataRecorded) {
+                            MenuItem item1 = menu.findItem(R.id.record_pause_data);
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/activity/MultimeterActivity.java]: There is a different icon for stop. Have a look at other instruments for the icon

**Comment by neel1998** [comment]
@CloudyPadmal  i have changed the stop icon. I think this can be merged now. 
Screenshot_20190601-140213
