### PR TITLE
upload script error fixed

### LINKED ISSUE #1901: Master branch Playstore APKs not being built
**Actual Behaviour**

Once a release is made (i.e. push to master), master apks should be generated and supply them to fastlane for Google Play store. Build is ending without proceeding to next steps from https://github.com/fossasia/pslab-android/blob/master/scripts/upload-apk.sh#L24

**Expected Behaviour**

Generate signed apks and fastlane sends them to Google Play

**Steps to reproduce it**

> Not available

**LogCat for the issue**

https://travis-ci.org/fossasia/pslab-android/builds/565944930#L1705

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

@neel1998

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1901

### CODE REVIEW

File: scripts/upload-apk.sh [hunk 1]
```diff
@@ -62,5 +62,5 @@ git push origin apk --force --quiet > /dev/null
 # Publish App to Play Store
 if [ "$TRAVIS_BRANCH" == "$PUBLISH_BRANCH" ]; then
     gem install fastlane
-    fastlane supply --aab pslab-master-app.aab --track alpha --json_key ../scripts/fastlane.json --package_name $PACKAGE_NAME
+    fastlane supply --aab pslab-master-app.aab --skip_upload_apk true --track alpha --json_key ../scripts/fastlane.json --package_name $PACKAGE_NAME
```
Comment (adityastic) [inline scripts/upload-apk.sh]: Skip upload does not matter when we use aab path
