### PR TITLE
Fixes #380 added linspace() to MathUtils

### LINKED ISSUE #380: create a MathUtils class to add frequently used Math functions
**Actual Behaviour**

Currently functions like map(), etc which are not available have to be written in each file.

**Expected Behaviour**

Create a MathUtil class which can have frequently used math functions like map(), linspace(), etc which are provided in numpy are ported in Java.

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by viveksb007**
Fixes issue #380 

Changes:
- Added implementation of linspace() from numpy to MathUtils Java.

### CODE REVIEW

File: app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java [hunk 1]
```diff
@@ -781,13 +782,18 @@ else if (args.contains("READ_CAP")) {
             for (int i = 0; i < samples; i++) {
                 this.buffer[i] = (listData.get(i * 2) | (listData.get(i * 2 + 1) << 8));
             }
+
+            /* Implementation moved to MathUtils
+
```
Comment (CloudyPadmal) [inline app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java]: Can't we remove this commented out code?

Comment (viveksb007) [inline app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java]: Yeah we can. Just kept it for reference to review the implementation.
