### PR TITLE
Lux meter indicator issue fixed

### LINKED ISSUE #1866: Value in the circular indicator doesn't change in lux meter
**Actual Behaviour**
The value stays fixed at 1 in the indicator

**Expected Behaviour**
Indicator should change according to the graph

**Steps to reproduce it**
Open lux meter

**Screenshots of the issue**

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by neel1998**
Fixes #1866 

**Changes**: Max value changed, some formatting in the code

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[lux.zip](https://github.com/fossasia/pslab-android/files/3391212/lux.zip)

### CODE REVIEW

File: app/src/main/java/io/pslab/fragment/LuxMeterDataFragment.java [hunk 1]
```diff
@@ -535,7 +529,7 @@ private void initiateLuxSensor(int type) {
                 if (sensor == null) {
                     Toast.makeText(getContext(), getResources().getString(R.string.no_lux_sensor), Toast.LENGTH_LONG).show();
                 } else {
-                    float max = sensor.getMaximumRange();
+                    float max = sensor.getMaximumRange() * 10000;
```
Comment (CloudyPadmal) [inline app/src/main/java/io/pslab/fragment/LuxMeterDataFragment.java]: This is the only related change right? Revert everything else back. Too many unnecessary changes moving stuff here and there.

Comment (neel1998) [reply app/src/main/java/io/pslab/fragment/LuxMeterDataFragment.java]: I had reformatted the file using [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>] thats why all those changes were made. I have reverted them now.
